recipes.remove(<tinker_io:SolidFuel>);
recipes.remove(<kitchensink:ItemMagnetT6>);
recipes.remove(<kitchensink:ItemMagnetT5>);
recipes.remove(<kitchensink:ItemMagnetT4>);
recipes.remove(<kitchensink:ItemMagnetT3>);
recipes.remove(<kitchensink:ItemMagnetT2>);
recipes.remove(<kitchensink:ItemMagnet>);
recipes.remove(<baublesstuff:Upgrade_Stone>);
recipes.remove(<avaritia:matrix_ingot>);
recipes.remove(<bloodmagic:BlockWall1:8>);
recipes.remove(<bloodmagic:BlockWall1:7>);
recipes.remove(<bloodmagic:BlockWall1:6>);
recipes.remove(<bloodmagic:BlockWall1:5>);
recipes.remove(<simplyjetpacks:itemJetpack:7>);
recipes.remove(<simplyjetpacks:itemJetpack:6>);
recipes.remove(<enderio:blockTransceiver>);
recipes.remove(<chickenchunks:chickenChunkLoader>);
recipes.remove(<chickenchunks:chickenChunkLoader:1>);
recipes.remove(<extrautils2:chunkloader>);
recipes.remove(<extrautils2:quarryproxy>);
recipes.remove(<extrautils2:quarry>);
recipes.remove(<rftools:shape_card:4>);
recipes.remove(<rftools:shape_card:7>);
recipes.remove(<mob_grinding_utils:saw_upgrade:4>);
recipes.remove(<mob_grinding_utils:saw_upgrade:3>);
recipes.remove(<mob_grinding_utils:saw_upgrade:2>);
recipes.remove(<mob_grinding_utils:saw_upgrade:1>);
recipes.remove(<mob_grinding_utils:saw_upgrade>);
recipes.remove(<mob_grinding_utils:absorption_upgrade>);
recipes.remove(<mob_grinding_utils:fan_upgrade:2>);
recipes.remove(<mob_grinding_utils:fan_upgrade:1>);
recipes.remove(<mob_grinding_utils:fan_upgrade>);
recipes.remove(<mob_grinding_utils:saw_upgrade:5>);
recipes.remove(<thermalfoundation:material:515>);
recipes.remove(<thermalfoundation:material:513>);
recipes.remove(<nuclearcraft:upgrade>);
recipes.remove(<nuclearcraft:part:2>);
recipes.remove(<nuclearcraft:part:1>);
recipes.remove(<nuclearcraft:cooler:7>);
recipes.remove(<nuclearcraft:cooler:6>);
recipes.remove(<nuclearcraft:cooler:5>);
recipes.remove(<nuclearcraft:cooler:4>);
recipes.remove(<nuclearcraft:cooler:4>);
recipes.remove(<nuclearcraft:cooler:1>);
recipes.remove(<nuclearcraft:cooler>);
recipes.remove(<nuclearcraft:cell_block>);
recipes.remove(<nuclearcraft:fission_block:1>);
recipes.remove(<nuclearcraft:fission_block>);
recipes.remove(<baublesstuff:Exp_Stuff>);
recipes.remove(<actuallyadditions:blockXPSolidifier>);
recipes.remove(<baublesstuff:BlockExpGenerator>);
recipes.remove(<baublesstuff:Pendant_Core>);
recipes.remove(<baublesstuff:Ring_NotLMagnet>);
recipes.remove(<baublesstuff:Ring_Magnet>);
recipes.remove(<baublesstuff:Ring_Core>);
recipes.remove(<immersiveengineering:wirecoil:1>);
recipes.remove(<baublesstuff:Belt_Core>);
recipes.remove(<immersiveengineering:material:5>);
recipes.remove(<immersiveengineering:wirecoil:3>);
recipes.remove(<bloodmagic:BlockWall1:9>);
recipes.remove(<bloodmagic:BlockDemonLight>);
recipes.remove(<bloodmagic:BlockDemonLight:3>);
recipes.remove(<bloodmagic:BlockDemonBricks2:3>);
recipes.remove(<bloodmagic:BlockDemonBricks2:2>);
recipes.remove(<bloodmagic:BlockDemonBricks2:1>);
recipes.remove(<bloodmagic:BlockDemonBricks2>);
recipes.remove(<bloodmagic:BlockDemonBricks2:4>);
recipes.remove(<immersiveengineering:bullet:2>);
recipes.remove(<simplyjetpacks:itemJetpack:10>);
recipes.remove(<simplyjetpacks:itemJetpack:2>);
recipes.remove(<simplyjetpacks:itemJetpack:3>);
recipes.remove(<simplyjetpacks:itemJetpack:4>);
recipes.remove(<simplyjetpacks:itemJetpack:5>);
recipes.remove(<bloodmagic:BlockDemonExtra:3>);
recipes.remove(<bloodmagic:BlockDemonExtra:1>);
recipes.remove(<bloodmagic:BlockDemonBricks2:13>);
recipes.remove(<bloodmagic:BlockDemonBricks2:14>);
recipes.remove(<bloodmagic:BlockDemonBricks2:12>);
recipes.remove(<bloodmagic:BlockDemonBricks2:10>);
recipes.remove(<bloodmagic:BlockDemonExtra>);
recipes.remove(<bloodmagic:BlockDemonBricks2:11>);
recipes.remove(<bloodmagic:BlockDemonExtra:2>);
recipes.remove(<bloodmagic:BlockDemonExtra:4>);
recipes.remove(<extrautils2:powertransmitter>);
recipes.remove(<extrautils2:flattransfernode:1>);
recipes.remove(<extrautils2:flattransfernode>);
recipes.remove(<extrautils2:grocket:2>);
recipes.remove(<extrautils2:grocket>);
recipes.remove(<minecraft:ender_eye>);
recipes.remove(<lteleporters:endercrystal>);
recipes.remove(<storagedrawers:compDrawers>);
recipes.remove(<rftools:charged_porter>);
recipes.remove(<immersiveengineering:drillhead>);
recipes.remove(<actuallyadditions:itemDrill:3>);
recipes.remove(<thermalexpansion:cache>);
recipes.remove(<thermalexpansion:dynamo>);
recipes.remove(<thermalexpansion:dynamo:1>);
recipes.remove(<thermalfoundation:material:514>);
recipes.remove(<refinedstorage:cable>);
recipes.remove(<thermalexpansion:frame:128>);
recipes.remove(<thermalfoundation:material:24>);
recipes.remove(<thermalexpansion:frame:64>);
recipes.remove(<thermalexpansion:frame>);
recipes.remove(<extrautils2:pipe>);
recipes.remove(<immersiveengineering:metalDevice1:6>);
recipes.remove(<advgenerators:TurbineRotorEnderium>);
recipes.remove(<advgenerators:TurbineBladeEnderium>);
recipes.remove(<extrautils2:passivegenerator:8>);
recipes.remove(<extrautils2:passivegenerator:2>);
recipes.remove(<extrautils2:passivegenerator:3>);
recipes.remove(<actuallyadditions:blockFarmer>);
recipes.remove(<actuallyadditions:itemDrillUpgradeFortuneII>);
recipes.remove(<actuallyadditions:itemDrillUpgradeFortune>);
recipes.remove(<actuallyadditions:itemDrillUpgradeFiveByFive>);
recipes.remove(<actuallyadditions:itemDrillUpgradeThreeByThree>);
recipes.remove(<actuallyadditions:itemDrillUpgradeSpeedIII>);
recipes.remove(<actuallyadditions:itemDrillUpgradeSpeedII>);
recipes.remove(<actuallyadditions:itemDrillUpgradeSpeed>);
recipes.remove(<vc:item_viesoline>);
recipes.remove(<vc:item_viesoline>);
recipes.remove(<enderio:itemBasicCapacitor:1>);
recipes.remove(<enderio:itemBasicCapacitor>);
recipes.remove(<harvestcraft:oliveoilitem>);
recipes.remove(<harvestcraft:oliveoilitem>);
recipes.remove(<harvestcraft:oliveoilitem>);
recipes.remove(<advgenerators:EuOutputIV>);
recipes.remove(<advgenerators:EuOutputEV>);
recipes.remove(<advgenerators:EuOutputHV>);
recipes.remove(<enderio:darkSteel_boots>);
recipes.remove(<enderio:darkSteel_leggings>);
recipes.remove(<enderio:darkSteel_chestplate>);
recipes.remove(<enderio:darkSteel_helmet>);
recipes.remove(<extrautils2:wateringcan:1000>);
recipes.remove(<armorplus:ender_dragon_arrow>);
recipes.remove(<minecraft:soul_sand>);
recipes.remove(<minecraft:hopper>);
recipes.remove(<openmodularturrets:ammo_meta:1> * 64);
recipes.remove(<kitchensink:QuarryBlock>);
recipes.remove(<enderio:itemMaterial:2>);
recipes.removeShapeless(<vc:item_viesoline>);
recipes.remove(<extrautils2:drum:2>);
recipes.remove(<translocator:translocator:1> * 2);
recipes.remove(<translocator:translocator> * 2);
recipes.remove(<enderio:itemBasicCapacitor:2>);
recipes.remove(<mysticalagriculture:base_essence_ingot>);
recipes.remove(<mysticalagriculture:infusion_crystal>);
recipes.remove(<extrautils2:goldenlasso>);
recipes.remove(<rftools:speedplus_module>);
recipes.remove(<rftools:flight_module>);
recipes.remove(<rftools:machine_frame>);
recipes.remove(<advgenerators:FuelTank>);
recipes.remove(<advgenerators:IronFrame>);
recipes.remove(<advgenerators:SteamTurbineController>);
recipes.remove(<advgenerators:SyngasController>);
recipes.remove(<advgenerators:ExchangerController>);
recipes.remove(<advgenerators:TurbineRotorAdvAlloy>);
recipes.remove(<advgenerators:TurbineRotorVibrant>);
recipes.remove(<advgenerators:TurbineRotorManyullyn>);
recipes.remove(<advgenerators:TurbineBladeAdvAlloy>);
recipes.remove(<advgenerators:TurbineBladeVibrant>);
recipes.remove(<advgenerators:TurbineBladeManyullyn>);
recipes.remove(<advgenerators:TurbineBronze>);
recipes.remove(<advgenerators:TurbineBladeBronze>);
recipes.remove(<advgenerators:TurbineKitBronze>);
recipes.remove(<advgenerators:TurbineRotorBronze>);
recipes.remove(<advgenerators:TurbineKitGold>);
recipes.remove(<advgenerators:TurbineRotorGold>);
recipes.remove(<advgenerators:TurbineGold>);
recipes.remove(<advgenerators:Controller>);
recipes.remove(<advgenerators:IronWiring>);
recipes.remove(<advgenerators:IronTubing>);
recipes.remove(<advgenerators:TurbineBladeManyullyn>);
recipes.remove(<advgenerators:TurbineBladeVibrant>);
recipes.remove(<advgenerators:TurbineBladeBronze>);
recipes.remove(<advgenerators:TurbineBladeAdvAlloy>);
recipes.remove(<advgenerators:TurbineBladeSteel>);
recipes.remove(<advgenerators:TurbineBladeIron>);
recipes.remove(<arsmagica2:spell_parchment>);
recipes.remove(<armorplus:workbench>);
recipes.remove(<colossalchests:colossalChest:3>);
recipes.remove(<colossalchests:colossalChest:2>);
recipes.remove(<colossalchests:colossalChest:5>);
recipes.remove(<colossalchests:colossalChest:4>);
recipes.remove(<colossalchests:colossalChest:1>);
recipes.remove(<colossalchests:interface:5>);
recipes.remove(<colossalchests:interface:3>);
recipes.remove(<colossalchests:interface:2>);
recipes.remove(<colossalchests:interface:1>);
recipes.remove(<colossalchests:interface:4>);
recipes.remove(<colossalchests:colossalChest>);
recipes.remove(<immersiveengineering:woodenDevice0>);
recipes.remove(<extrautils2:teleporter:1>);
recipes.remove(<refinedstorage:solderer>);
recipes.remove(<minecraft:bookshelf>);
recipes.remove(<harvestcraft:market>);
recipes.remove(<xreliquary:alkahestry_tome:1001>);
recipes.remove(<xreliquary:fertile_lilypad>);
recipes.remove(<xreliquary:phoenix_down>);
recipes.remove(<xreliquary:interdiction_torch>);
recipes.remove(<xreliquary:twilight_cloak>);
recipes.remove(<xreliquary:lantern_of_paranoia>);
recipes.remove(<xreliquary:angelheart_vial>);
recipes.remove(<xreliquary:angelic_feather>);
recipes.remove(<xreliquary:rending_gale>);
recipes.remove(<rftools:shape_card:2>);
recipes.remove(<rftools:builder>);
recipes.remove(<ic2:jetpack_electric>);
recipes.remove(<ic2:jetpack_electric:26>);
recipes.remove(<ic2:jetpack:27>);
recipes.remove(<ic2:jetpack:1>);
recipes.remove(<ic2:batpack>);
recipes.remove(<ic2:advanced_batpack:26>);
recipes.remove(<ic2:advanced_batpack>);
recipes.remove(<ic2:batpack:26>);
recipes.remove(<armorplus:chainmail>);
recipes.remove(<bigreactors:reactorcontrolrod>);
recipes.remove(<bigreactors:reactorfuelrod>);
recipes.remove(<rftools:screen>);
recipes.remove(<rftools:machine_base>);
recipes.remove(<bigreactors:reactorcontroller>);
recipes.remove(<bigreactors:reactorcasing>);
recipes.remove(<bigreactors:reactorcasingcores>);
recipes.remove(<ic2:plate:2>);
recipes.remove(<extrautils2:angelring>);
recipes.remove(<extrautils2:angelring:1>);
recipes.remove(<extrautils2:angelring:2>);
recipes.remove(<extrautils2:angelring:3>);
recipes.remove(<extrautils2:angelring:4>);
recipes.remove(<extrautils2:angelring:5>);
recipes.remove(<ironbackpacks:basicBackpack>);
recipes.remove(<enderio:itemMachinePart:1>);
recipes.remove(<mysticalagriculture:infusion_crystal>);
recipes.remove(<immersiveengineering:wirecoil>);
recipes.remove(<immersiveengineering:wirecoil:4>);
recipes.remove(<immersiveengineering:material:23>);
recipes.remove(<mysticalagriculture:growth_accelerator>);
recipes.remove(<minecraft:furnace>);
recipes.remove(<mikedongles:watering_dongle>);
recipes.remove(<agricraft:sprinkler>);
recipes.remove(<minecraft:piston>);
recipes.remove(<actuallyadditions:blockAtomicReconstructor>);
recipes.remove(<actuallyadditions:blockMisc:9>);
recipes.remove(<armorplus:steel_ingot>);
recipes.remove(<enderio:itemMachinePart>);
recipes.remove(<stevescarts:ModuleComponents:33>);
recipes.remove(<minecraft:chest>);
recipes.remove(<minecraft:bucket>);
recipes.remove(<immersiveengineering:stoneDecoration:1> * 2);
recipes.remove(<bigreactors:reactorcontrolrod>);
recipes.remove(<mikedongles:watering_dongle>);
recipes.remove(<kitchensink:deathsSythe>);
recipes.remove(<immersiveengineering:metalDevice1:13>);


mods.armorplus.HighTechBench.remove(<armorplus:the_ultimate_material>);

recipes.addShapeless(<stevescarts:ModuleComponents:33>, [<ore:nuggetAluminum>, <ore:nuggetAluminum>]);
recipes.addShapeless(<refinedstorage:cable> * 6, [<titantrinkets:Discblockthree>]);
recipes.addShapeless(<refinedstorage:storage_disk:3>.withTag({Items: [], Stored: 0, Protocol: 1}), [<bloodmagic:BlockDemonExtra:2>]);
recipes.addShapeless(<refinedstorage:storage_disk:2>.withTag({Items: [], Stored: 0, Protocol: 1}), [<bloodmagic:BlockDemonExtra>]);
recipes.addShapeless(<armorplus:chainmail>, [<immersiveengineering:metal:24>, <immersiveengineering:metal:24>]);
recipes.addShapeless(<armorplus:chainmail>, [<ore:nuggetSilver>, <ore:nuggetSilver>]);
recipes.addShapeless(<harvestcraft:oliveoilitem>, [<arsmagica2:item_ore:8>]);
recipes.addShapeless(<openmodularturrets:laser_turret>, [<titantrinkets:Turrett5>]);
recipes.addShapeless(<openmodularturrets:rail_gun_turret>, [<titantrinkets:Turretbaset5>]);
recipes.addShapeless(<openmodularturrets:upgrade_meta:1>, [<titantrinkets:TurretAmmo2>, <minecraft:redstone>]);
recipes.addShapeless(<openmodularturrets:upgrade_meta:2>, [<titantrinkets:TurretAmmo2>, <minecraft:feather>]);
recipes.addShapeless(<openmodularturrets:upgrade_meta:3>, [<titantrinkets:TurretAmmo2>, <minecraft:glass>]);
recipes.addShapeless(<openmodularturrets:addon_meta:3>, [<titantrinkets:TurretAmmo2>, <minecraft:bone>]);
recipes.addShapeless(<openmodularturrets:addon_meta:1>, [<titantrinkets:TurretAmmo2>, <minecraft:stone_sword>]);
recipes.addShapeless(<openmodularturrets:ammo_meta:2> * 64, [<titantrinkets:TurretAmmo1>]);
recipes.addShapeless(<refinedstorage:processor:4> * 10, [<titantrinkets:Componentblocktwo>]);
recipes.addShapeless(<refinedstorage:processor:3> * 10, [<titantrinkets:Componentblockthree>]);
recipes.addShapeless(<refinedstorage:processor:5> * 10, [<titantrinkets:Componentblockone>]);
recipes.addShapeless(<minecraft:fish:3>, [<ore:feather>, <ore:listAllfishraw>, <ore:feather>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<armorplus:super_star_helmet:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<armorplus:super_star_chestplate:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<armorplus:super_star_boots:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<armorplus:super_star_leggings:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<armorplus:super_star_sword:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<armorplus:super_star_battle_axe:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<armorplus:super_star_bow:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<armorplus:guardian_helmet:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<armorplus:guardian_chestplate:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<armorplus:guardian_boots:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<armorplus:guardian_leggings:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<armorplus:guardian_sword:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<armorplus:guardian_battle_axe:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<armorplus:guardian_bow:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<minecraft:golden_chestplate:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<minecraft:golden_leggings:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<minecraft:golden_boots:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<minecraft:golden_sword:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<minecraft:golden_helmet:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<minecraft:iron_chestplate:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<minecraft:iron_leggings:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<minecraft:iron_boots:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<minecraft:iron_sword:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<minecraft:iron_helmet:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<minecraft:chainmail_chestplate:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<minecraft:chainmail_leggings:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<minecraft:chainmail_boots:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<minecraft:chainmail_helmet:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<minecraft:diamond_chestplate:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<minecraft:diamond_leggings:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<minecraft:diamond_boots:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<minecraft:diamond_sword:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<minecraft:diamond_helmet:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<minecraft:leather_chestplate:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<minecraft:leather_leggings:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<minecraft:leather_boots:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<minecraft:stone_sword:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<minecraft:leather_helmet:*>]);
recipes.addShapeless(<ic2:crafting:24> * 3, [<minecraft:bow:*>]);
recipes.addShapeless(<minecraft:lapis_block> * 2, [<armorplus:lapis_helmet:*>]);
recipes.addShapeless(<minecraft:lapis_block> * 2, [<armorplus:lapis_chestplate:*>]);
recipes.addShapeless(<minecraft:lapis_block> * 2, [<armorplus:lapis_leggings:*>]);
recipes.addShapeless(<minecraft:lapis_block> * 2, [<armorplus:lapis_boots:*>]);
recipes.addShapeless(<minecraft:redstone_block> * 2, [<armorplus:redstone_helmet:*>]);
recipes.addShapeless(<minecraft:redstone_block> * 2, [<armorplus:redstone_chestplate:*>]);
recipes.addShapeless(<minecraft:redstone_block> * 2, [<armorplus:redstone_leggings:*>]);
recipes.addShapeless(<minecraft:redstone_block> * 2, [<armorplus:redstone_boots:*>]);
recipes.addShapeless(<tinker_io:SolidFuel> * 8, [<dmonsters:dump>, <ore:fuelCoke>, <dmonsters:dump>, <dmonsters:dump>]);
recipes.addShapeless(<harvestcraft:cocoapowderitem>, [<dmonsters:dump>, <ore:listAllsugar>, <ore:listAllsugar>]);
recipes.addShapeless(<ic2:resource:11> * 2, [<tconstruct:soil>, <ore:stone>]);
recipes.addShapeless(<openmodularturrets:expander:4>, [<bloodmagic:BlockDemonBricks2:4>, <minecraft:clay>]);
recipes.addShapeless(<openmodularturrets:upgrade_meta:4>, [<bloodmagic:BlockDemonBricks2:4>, <ore:cobblestone>]);
recipes.addShapeless(<openmodularturrets:upgrade_meta:2>, [<bloodmagic:BlockDemonBricks2:4>, <ore:blockGlassColorless>]);
recipes.addShapeless(<openmodularturrets:addon_meta:6>, [<bloodmagic:BlockDemonBricks2:4>, <ore:gravel>]);
recipes.addShapeless(<openmodularturrets:addon_meta:3>, [<bloodmagic:BlockDemonBricks2:4>, <ore:sand>]);
recipes.addShapeless(<openmodularturrets:addon_meta:1>, [<bloodmagic:BlockDemonBricks2:4>, <ore:dirt>]);
recipes.addShapeless(<openmodularturrets:ammo_meta:4> * 64, [<bloodmagic:BlockDemonLight:3>]);
recipes.addShapeless(<openmodularturrets:ammo_meta:2> * 64, [<bloodmagic:BlockDemonLight>]);
recipes.addShapeless(<openmodularturrets:rocket_turret>, [<bloodmagic:BlockDemonBricks2:3>]);
recipes.addShapeless(<openmodularturrets:rail_gun_turret>, [<bloodmagic:BlockDemonBricks2:2>]);
recipes.addShapeless(<openmodularturrets:laser_turret>, [<bloodmagic:BlockDemonBricks2:1>]);
recipes.addShapeless(<refinedstorage:pattern> * 6, [<bloodmagic:BlockDemonBricks2>, <minecraft:paper>]);
recipes.addShapeless(<refinedstorage:grid:1>, [<bloodmagic:BlockDemonBricks2>, <minecraft:crafting_table>]);
recipes.addShapeless(<refinedstorage:processor:4> * 6, [<bloodmagic:BlockDemonBricks2>, <ore:bone>]);
recipes.addShapeless(<refinedstorage:core> * 8, [<bloodmagic:BlockDemonBricks2>, <minecraft:feather>]);
recipes.addShapeless(<refinedstorage:processor:4> * 8, [<bloodmagic:BlockDemonExtra:4>]);
recipes.addShapeless(<refinedstorage:processor:5> * 8, [<bloodmagic:BlockDemonExtra:3>]);
recipes.addShapeless(<refinedstorage:cable> * 6, [<bloodmagic:BlockDemonExtra:1>]);
recipes.addShapeless(<refinedstorage:storage_disk:3>, [<bloodmagic:BlockDemonExtra:2>]);
recipes.addShapeless(<refinedstorage:storage_disk:2>, [<bloodmagic:BlockDemonExtra>]);
recipes.addShapeless(<extrautils2:powertransmitter>, [<ore:gearRedstone>, <enderio:itemFunctionUpgrade>]);
recipes.addShapeless(<refinedstorage:cable> * 2, [<ore:itemRubber>, <ore:itemRubber>, <refinedstorage:quartz_enriched_iron>]);
recipes.addShapeless(<minecraft:ender_pearl> * 3, [<thermalexpansion:augment:322>]);
recipes.addShapeless(<thermalfoundation:material:193> * 9, [<ore:ingotTin>]);

mods.armorplus.HighTechBench.addShapeless(<armorplus:the_ultimate_material>, [<armorplus:ender_dragon_scale>, <armorplus:lava_crystal:1>, <armorplus:guardian_scale>, <armorplus:wither_bone>, <minefactoryreloaded:pink_slime:1>, <thermalfoundation:material:1026>]);


recipes.addShaped(<titantrinkets:ExtremeMaterial>, [[<thermalfoundation:storage_alloy:7>, <tconstruct:metal:2>, <thermalfoundation:storage_alloy:7>], [<tconstruct:metal:2>, <thermalfoundation:storage_alloy:7>, <tconstruct:metal:2>], [<thermalfoundation:storage_alloy:7>, <tconstruct:metal:2>, <thermalfoundation:storage_alloy:7>]]);
recipes.addShaped(<extrautils2:drum:2>, [[<ic2:plate:11>, <ore:plateDenseGold>, <ic2:plate:11>], [<minecraft:diamond_block>, <ore:blockMythril>, <ore:blockDiamond>], [<ic2:plate:11>, <ic2:plate:11>, <ic2:plate:11>]]);
recipes.addShaped(<translocator:translocator> * 2, [[<ore:dustRedstone>, <ore:ingotTin>, <ore:dustRedstone>], [<enderio:itemAlloy:2>, <minecraft:structure_void>, <enderio:itemAlloy:2>], [<ore:dustRedstone>, <ore:ingotTin>, <ore:dustRedstone>]]);
recipes.addShaped(<translocator:translocator:1> * 2, [[<ore:dustRedstone>, <minecraft:dye:4>, <ore:dustRedstone>], [<enderio:itemAlloy:2>, <minecraft:structure_void>, <enderio:itemAlloy:2>], [<ore:dustRedstone>, <minecraft:dye:4>, <ore:dustRedstone>]]);
recipes.addShaped(<enderio:itemBasicCapacitor:2>, [[null, <enderio:itemAlloy:2>, null], [<enderio:itemBasicCapacitor:1>, <sccraftingrunes:ItemCommonMat>, <enderio:itemBasicCapacitor:1>], [null, <enderio:itemAlloy:2>, null]]);
recipes.addShaped(<mysticalagriculture:base_essence_ingot>, [[null, <mysticalagriculture:prosperity_shard>, null], [<mysticalagriculture:prosperity_shard>, <sccraftingrunes:ItemCommonMat>, <mysticalagriculture:prosperity_shard>], [null, <mysticalagriculture:prosperity_shard>, null]]);
recipes.addShaped(<mysticalagriculture:infusion_crystal>, [[<mysticalagriculture:inferium_essence>, <mysticalagriculture:prosperity_shard>, <mysticalagriculture:inferium_essence>], [<mysticalagriculture:prosperity_shard>, <minecraft:structure_void>, <mysticalagriculture:prosperity_shard>], [<mysticalagriculture:inferium_essence>, <mysticalagriculture:prosperity_shard>, <mysticalagriculture:inferium_essence>]]);
recipes.addShaped(<minecraft:structure_void>, [[<ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>], [<ore:gemLapis>, <sccraftingrunes:ItemCommonMat>, <ore:gemLapis>], [<ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>]]);
recipes.addShaped(<extrautils2:goldenlasso>, [[null, <ore:ingotGold>, null], [<minecraft:gold_ingot>, <sccraftingrunes:ItemCommonMat>, <minecraft:gold_ingot>], [null, <immersiveengineering:material:5>, null]]);
recipes.addShaped(<rftools:speedplus_module>, [[<ore:ingotLead>, <ore:ingotLead>, <ore:ingotLead>], [<ic2:plate:11>, <ore:ingotLead>, <ic2:plate:11>], [<adinferos:infernal_feather>, <ore:ingotLead>, <adinferos:infernal_feather>]]);
recipes.addShaped(<rftools:flight_module>, [[<adinferos:infernal_feather>, <ore:ingotMythril>, <adinferos:infernal_feather>], [<ore:ingotMythril>, <ore:ingotMythril>, <ore:plateDenseGold>], [<adinferos:infernal_feather>, <ore:plateDenseGold>, <adinferos:infernal_feather>]]);
recipes.addShaped(<rftools:machine_frame>, [[<ore:plateLead>, <ore:plateLead>, <ore:plateLead>], [<ore:plateLead>, null, <ore:plateLead>], [<ore:plateLead>, <ore:plateLead>, <ore:plateLead>]]);
recipes.addShaped(<advgenerators:ForgeOutput>, [[<advgenerators:IronFrame>, <ore:plateBronze>, <advgenerators:IronFrame>], [<ore:plateBronze>, <advgenerators:PowerIO>, <ore:plateBronze>], [<advgenerators:IronFrame>, <ore:plateBronze>, <advgenerators:IronFrame>]]);
recipes.addShaped(<advgenerators:FuelTank>, [[<ore:plateSteel>, <advgenerators:IronFrame>, <ore:plateSteel>], [<advgenerators:IronFrame>, <itank:tank>, <advgenerators:IronFrame>], [<ore:plateSteel>, <advgenerators:IronFrame>, <ore:plateSteel>]]);
recipes.addShaped(<advgenerators:FluidInput>, [[<ore:plateSteel>, null, <ore:plateSteel>], [<advgenerators:IronFrame>, <ore:plateSteel>, <advgenerators:IronFrame>], [null, <itank:tank>, null]]);
recipes.addShaped(<advgenerators:IronFrame> *4, [[<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>], [<ore:ingotIron>, null, <ore:ingotIron>], [<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>]]);
recipes.addShaped(<advgenerators:ExchangerController>, [[<advgenerators:IronFrame>, <advgenerators:IronWiring>, <advgenerators:IronFrame>], [<advgenerators:IronTubing>, <titantrinkets:WitherTitanCatalyst>, <advgenerators:IronTubing>], [<advgenerators:IronFrame>, <advgenerators:IronWiring>, <advgenerators:IronFrame>]]);
recipes.addShaped(<advgenerators:SyngasController>, [[<advgenerators:IronFrame>, <advgenerators:IronWiring>, <advgenerators:IronFrame>], [<advgenerators:IronTubing>, <titantrinkets:WitherTitanCatalyst>, <advgenerators:IronTubing>], [<advgenerators:IronFrame>, <advgenerators:IronTubing>, <advgenerators:IronFrame>]]);
recipes.addShaped(<advgenerators:SteamTurbineController>, [[<advgenerators:IronFrame>, <advgenerators:PressureValve>, <advgenerators:IronFrame>], [<advgenerators:IronWiring>, <titantrinkets:WitherTitanCatalyst>, <advgenerators:IronWiring>], [<advgenerators:IronFrame>, <advgenerators:IronTubing>, <advgenerators:IronFrame>]]);
recipes.addShaped(<advgenerators:TurbineRotorManyullyn>, [[<advgenerators:TurbineBladeManyullyn>, <advgenerators:TurbineBladeManyullyn>, <advgenerators:TurbineBladeManyullyn>], [<advgenerators:TurbineBladeManyullyn>, <titantrinkets:WitherTitanCatalyst>, <advgenerators:TurbineBladeManyullyn>], [<advgenerators:TurbineBladeManyullyn>, <advgenerators:TurbineBladeManyullyn>, <advgenerators:TurbineBladeManyullyn>]]);
recipes.addShaped(<advgenerators:TurbineRotorVibrant>, [[<advgenerators:TurbineBladeVibrant>, <advgenerators:TurbineBladeVibrant>, <advgenerators:TurbineBladeVibrant>], [<advgenerators:TurbineBladeVibrant>, <titantrinkets:WitherTitanCatalyst>, <advgenerators:TurbineBladeVibrant>], [<advgenerators:TurbineBladeVibrant>, <advgenerators:TurbineBladeVibrant>, <advgenerators:TurbineBladeVibrant>]]);
recipes.addShaped(<advgenerators:TurbineRotorAdvAlloy>, [[<advgenerators:TurbineBladeAdvAlloy>, <advgenerators:TurbineBladeAdvAlloy>, <advgenerators:TurbineBladeAdvAlloy>], [<advgenerators:TurbineBladeAdvAlloy>, <titantrinkets:WitherTitanCatalyst>, <advgenerators:TurbineBladeAdvAlloy>], [<advgenerators:TurbineBladeAdvAlloy>, <advgenerators:TurbineBladeAdvAlloy>, <advgenerators:TurbineBladeAdvAlloy>]]);
recipes.addShaped(<advgenerators:TurbineBladeAdvAlloy> * 2, [[<ic2:crafting:3>, <ic2:crafting:3>], [<ic2:crafting:3>, <ic2:crafting:3>], [null, <ic2:crafting:3>]]);
recipes.addShaped(<advgenerators:TurbineBladeVibrant> * 2, [[<ore:ingotVibrantAlloy>, <enderio:itemAlloy:2>], [<ore:ingotVibrantAlloy>, <enderio:itemAlloy:2>], [null, <ore:ingotVibrantAlloy>]]);
recipes.addShaped(<advgenerators:TurbineBladeManyullyn> * 2, [[<ore:ingotManyullyn>, <tconstruct:ingots:2>], [<ore:ingotManyullyn>, <tconstruct:ingots:2>], [null, <ore:ingotManyullyn>]]);
recipes.addShaped(<titantrinkets:WitherTitanCatalyst>, [[<bigreactors:minerals:1>, <bigreactors:minerals:1>, <bigreactors:minerals:1>], [<ore:netherStar>, <ore:eyeofredstone>, <ore:netherStar>], [<bigreactors:minerals:1>, <bigreactors:minerals:1>, <bigreactors:minerals:1>]]);
recipes.addShaped(<advgenerators:Controller>, [[<ore:plateIron>, <titantrinkets:RefinedRedstone>, <ore:plateIron>], [<titantrinkets:RefinedRedstone>, <ore:gemDiamond>, <titantrinkets:RefinedRedstone>], [<ore:plateIron>, <titantrinkets:RefinedRedstone>, <ore:plateIron>]]);
recipes.addShaped(<advgenerators:IronWiring> * 4, [[null, <titantrinkets:RefinedRedstone>, <ore:stickTreatedWood>], [<titantrinkets:RefinedRedstone>, <ore:plankTreatedWood>, <titantrinkets:RefinedRedstone>], [<ore:stickTreatedWood>, <titantrinkets:RefinedRedstone>, null]]);
recipes.addShaped(<advgenerators:IronTubing> * 4, [[null, <ore:plateIron>, <ore:stickTreatedWood>], [<ore:plateIron>, <ore:plankTreatedWood>, <ore:plateIron>], [<ore:stickTreatedWood>, <ore:plateIron>, null]]);
recipes.addShaped(<advgenerators:TurbineBladeSteel> * 2, [[<ore:plateSteel>, <ore:plateSteel>], [<ore:plateSteel>, <ore:plateSteel>], [null, <ore:plateSteel>]]);
recipes.addShaped(<advgenerators:TurbineBladeIron> * 2, [[<ore:plateIron>, <ore:plateIron>], [<ore:plateIron>, <ore:plateIron>], [null, <ore:plateIron>]]);
recipes.addShaped(<arsmagica2:spell_parchment>, [[<ore:stickTreatedWood>], [<immersiveengineering:material:5>], [<ore:stickTreatedWood>]]);
recipes.addShaped(<armorplus:workbench>, [[<minecraft:lapis_block>, <ore:blockLapis>, <ore:blockLapis>], [<actuallyadditions:blockMisc:2>, <ic2:te:88>, <actuallyadditions:blockMisc:2>], [<actuallyadditions:blockMisc:2>, null, <actuallyadditions:blockMisc:2>]]);

recipes.addShaped(<colossalchests:interface:5>, [[null, <minecraft:lapis_block>, null], [<minecraft:lapis_block>, <colossalchests:chestWall:5>, <minecraft:lapis_block>], [null, <minecraft:lapis_block>, null]]);
recipes.addShaped(<colossalchests:interface:4>, [[null, <minecraft:lapis_block>, null], [<minecraft:lapis_block>, <colossalchests:chestWall:4>, <minecraft:lapis_block>], [null, <minecraft:lapis_block>, null]]);
recipes.addShaped(<colossalchests:interface:3>, [[null, <minecraft:lapis_block>, null], [<minecraft:lapis_block>, <colossalchests:chestWall:3>, <minecraft:lapis_block>], [null, <minecraft:lapis_block>, null]]);
recipes.addShaped(<colossalchests:interface:2>, [[null, <minecraft:lapis_block>, null], [<minecraft:lapis_block>, <colossalchests:chestWall:2>, <minecraft:lapis_block>], [null, <minecraft:lapis_block>, null]]);
recipes.addShaped(<colossalchests:interface:1>, [[null, <minecraft:lapis_block>, null], [<minecraft:lapis_block>, <colossalchests:chestWall:1>, <minecraft:lapis_block>], [null, <minecraft:lapis_block>, null]]);
recipes.addShaped(<colossalchests:colossalChest:5>, [[<ore:blockRedstone>, null, <ore:blockRedstone>], [null, <colossalchests:chestWall:5>, null], [<ore:blockRedstone>, null, <ore:blockRedstone>]]);
recipes.addShaped(<colossalchests:colossalChest:4>, [[<ore:blockRedstone>, null, <ore:blockRedstone>], [null, <colossalchests:chestWall:4>, null], [<ore:blockRedstone>, null, <ore:blockRedstone>]]);
recipes.addShaped(<colossalchests:colossalChest:3>, [[<ore:blockRedstone>, null, <ore:blockRedstone>], [null, <colossalchests:chestWall:3>, null], [<ore:blockRedstone>, null, <ore:blockRedstone>]]);
recipes.addShaped(<colossalchests:colossalChest:2>, [[<ore:blockRedstone>, null, <ore:blockRedstone>], [null, <colossalchests:chestWall:2>, null], [<ore:blockRedstone>, null, <ore:blockRedstone>]]);
recipes.addShaped(<colossalchests:colossalChest:1>, [[<ore:blockRedstone>, null, <ore:blockRedstone>], [null, <colossalchests:chestWall:1>, null], [<ore:blockRedstone>, null, <ore:blockRedstone>]]);
recipes.addShaped(<colossalchests:colossalChest>, [[<ore:blockRedstone>, null, <ore:blockRedstone>], [null, <colossalchests:chestWall>, null], [<ore:blockRedstone>, null, <ore:blockRedstone>]]);
recipes.addShaped(<immersiveengineering:stoneDecoration:1> * 2, [[<ore:sandstone>, <ore:ingotBrick>, <ore:sandstone>], [<ore:ingotBrick>, <ore:fuelCoke>, <ore:ingotBrick>], [<ore:sandstone>, <ore:ingotBrick>, <ore:sandstone>]]);
recipes.addShaped(<titantrinkets:AirshipEngine2>, [[<ore:blockDarkSteel>, <ore:blockLudicrite>, <ore:blockDarkSteel>], [<ore:blockDarkSteel>, <enderio:blockIngotStorage:6>, <ore:blockDarkSteel>], [<teslacorelib:gear_diamond>, <titantrinkets:DarkTitanRelic>, <teslacorelib:gear_diamond>]]);
recipes.addShaped(<titantrinkets:AirshipEngine1>, [[<ore:blockDarkSteel>, <ore:blockMythril>, <ore:blockDarkSteel>], [<enderio:blockIngotStorage:6>, <immersiveengineering:metalDevice0:2>, <ore:blockDarkSteel>], [null, <enderio:blockIngotStorage:6>, null]]);
recipes.addShaped(<vc:item_viesoline>* 4, [[<ore:dustRedstone>, <ore:itemCharcoal>, <ore:dustRedstone>], [<ore:itemCharcoal>, <forge:bucketFilled>.withTag({FluidName:"rocket_fuel", Amount:1000}), <ore:itemCharcoal>], [<ore:dustRedstone>, <ore:itemCharcoal>, <ore:dustRedstone>]]);
recipes.addShaped(<minecraft:furnace>, [[<ore:compressed1xCobblestone>, <extrautils2:compressedcobblestone>, <ore:compressed1xCobblestone>], [<extrautils2:compressedcobblestone>, null, <ore:compressed1xCobblestone>], [<ore:compressed1xCobblestone>, <ore:compressed1xCobblestone>, <ore:compressed1xCobblestone>]]);
recipes.addShaped(<enderio:itemMachinePart:1>, [[null, <ore:ingotTin>, null], [<ore:ingotTin>, <minecraft:stick>, <ore:ingotTin>], [null, <ore:ingotTin>, null]]);
recipes.addShaped(<immersiveengineering:wirecoil>, [[<ore:wireCopper>, <ore:wireCopper>, <ore:wireCopper>], [<ore:wireCopper>, <ore:stickTreatedWood>, <ore:wireCopper>], [<ore:wireCopper>, <ore:wireCopper>, <ore:wireCopper>]]);
recipes.addShaped(<refinedstorage:solderer>, [[<stevescarts:ModuleComponents:49>, <advanced_solar_panels:crafting:9>, <stevescarts:ModuleComponents:49>], [<stevescarts:ModuleComponents:49>, null, <stevescarts:ModuleComponents:49>], [<stevescarts:ModuleComponents:49>, <advanced_solar_panels:crafting:9>, <stevescarts:ModuleComponents:49>]]);
recipes.addShaped(<minecraft:bookshelf>, [[<ore:plankTreatedWood>, <ore:plankTreatedWood>, <ore:plankTreatedWood>], [<minecraft:book>, <minecraft:book>, <minecraft:book>], [<ore:plankTreatedWood>, <immersiveengineering:treatedWood>, <ore:plankTreatedWood>]]);
recipes.addShaped(<guideapi:ItemGuideBook:1>, [[<ore:slimeballBlood>, <tconstruct:edible:3>, <ore:slimeballBlood>], [<ore:slimeballBlood>, <guideapi:ItemGuideBook>, <ore:slimeballBlood>], [<ore:slimeballBlood>, <ore:slimeballBlood>, <ore:slimeballBlood>]]);
recipes.addShaped(<guideapi:ItemGuideBook>, [[<ore:slimeballBlood>, <ore:slimeballBlood>, <ore:slimeballBlood>], [<ore:slimeballBlood>, <minecraft:book>, <ore:slimeballBlood>], [<ore:slimeballBlood>, <ore:slimeballBlood>, <ore:slimeballBlood>]]);
recipes.addShaped(<xreliquary:lantern_of_paranoia>, [[<xreliquary:mob_ingredient:1>, <xreliquary:mob_ingredient:7>, <xreliquary:mob_ingredient:1>], [<minecraft:glass>, <xreliquary:interdiction_torch>, <minecraft:glass>], [<minecraft:glass>, <xreliquary:mob_ingredient:7>, <minecraft:glass>]]);
recipes.addShaped(<xreliquary:interdiction_torch>, [[<vc:achievements/achievement_airship_portal>], [<xreliquary:mob_ingredient>], [<xreliquary:mob_ingredient>]]);
recipes.addShaped(<ic2:jetpack_electric:26>, [[<ic2:crafting:3>, <extrautils2:opinium:4>, <ic2:crafting:3>], [<minecraft:fireworks>, <titantrinkets:DragonTitanCatalyst>, <minecraft:fireworks>], [<ic2:crafting:3>, null, <ic2:crafting:3>]]);
recipes.addShaped(<minecraft:name_tag>, [[null, <ore:chainmail>], [<immersiveengineering:treatedWoodSlab>, null]]);
recipes.addShaped(<armorplus:chainmail>, [[<ore:nugget_tin>, <ore:nugget_tin>, null], [<ore:nugget_tin>, <ore:nugget_tin>, <ore:nugget_tin>], [null, <ore:nugget_tin>, <ore:nugget_tin>]]);
recipes.addShaped(<beneath:teleporterbeneath>, [[<minecraft:lapis_block>, <armorplus:compressed_obsidian>, <minecraft:lapis_block>], [<armorplus:compressed_obsidian>, <bloodmagic:ItemBloodOrb:2>, <armorplus:compressed_obsidian>], [<minecraft:lapis_block>, <armorplus:compressed_obsidian>, <minecraft:lapis_block>]]);
recipes.addShaped(<bigreactors:reactorcontrolrod>, [[<bigreactors:reactorcasing>, <simpleores:mythril_ingot>, <bigreactors:reactorcasing>], [<simpleores:mythril_ingot>, <ore:ingotUranium>, <simpleores:mythril_ingot>], [<bigreactors:reactorcasing>, <ore:ingotRedstoneAlloy>, <bigreactors:reactorcasing>]]);
recipes.addShaped(<bigreactors:reactorfuelrod>, [[<enderio:blockFusedQuartz>, <simpleores:mythril_ingot>, <enderio:blockFusedQuartz>], [<enderio:blockFusedQuartz>, <ore:ingotUranium>, <enderio:blockFusedQuartz>], [<enderio:blockFusedQuartz>, <simpleores:mythril_ingot>, <enderio:blockFusedQuartz>]]);
recipes.addShaped(<rftools:screen>, [[<enderio:blockFusedQuartz>, <enderio:blockFusedQuartz>, <enderio:blockFusedQuartz>], [<enderio:blockFusedQuartz>, <rftools:machine_base>, <enderio:blockFusedQuartz>], [<ore:ingotAluminum>, <ore:ingotAluminum>, <ore:ingotAluminum>]]);
recipes.addShaped(<rftools:machine_base>, [[<ore:dustRedstone>, <ore:dustRedstone>, <ore:dustRedstone>], [<ore:ingotLead>, <ore:ingotLead>, <ore:ingotLead>]]);
recipes.addShaped(<bigreactors:reactorcontroller>, [[<bigreactors:reactorcasing>, <enderio:itemAlloy:3>, <bigreactors:reactorcasing>], [<titantrinkets:RefinedGraphite>, <rftools:screen>, <titantrinkets:RefinedGraphite>], [<bigreactors:reactorcasing>, <enderio:itemAlloy:3>, <bigreactors:reactorcasing>]]);
recipes.addShaped(<bigreactors:reactorcasingcores>, [[<titantrinkets:RefinedGraphite>, <bigreactors:minerals>, <titantrinkets:RefinedGraphite>], [<bigreactors:minerals>, <enderio:itemAlloy:3>, <bigreactors:minerals>], [<titantrinkets:RefinedGraphite>, <bigreactors:minerals>, <titantrinkets:RefinedGraphite>]]);
recipes.addShaped(<bigreactors:reactorcasing> * 4, [[<titantrinkets:RefinedGraphite>, <ore:ingotUranium>, <titantrinkets:RefinedGraphite>], [<ore:plateDenseLead>, <bigreactors:reactorcasingcores>, <ore:plateDenseLead>], [<titantrinkets:RefinedGraphite>, <ore:ingotUranium>, <titantrinkets:RefinedGraphite>]]);
recipes.addShaped(<titantrinkets:DragonTitanCatalyst>, [[<bigreactors:minerals:1>, <ore:netherStar>, <bigreactors:minerals:1>], [<bigreactors:minerals:1>, <minecraft:skull:5>, <bigreactors:minerals:1>], [<bigreactors:minerals:1>, <bigreactors:minerals:1>, <bigreactors:minerals:1>]]);
recipes.addShaped(<extrautils2:angelring:1>, [[<ore:dyeGray>, <extrautils2:angelring>, <ore:dyeGray>]]);
recipes.addShaped(<extrautils2:angelring:5>, [[<ore:dyeBlack>, <extrautils2:angelring>, <ore:dyeBlack>]]);
recipes.addShaped(<extrautils2:angelring:4>, [[<ore:dyeYellow>, <extrautils2:angelring>, <ore:dyeYellow>]]);
recipes.addShaped(<extrautils2:angelring:3>, [[<ore:dyeRed>, <extrautils2:angelring>, <ore:dyeRed>]]);
recipes.addShaped(<extrautils2:angelring:2>, [[<ore:dyePink>, <extrautils2:angelring>, <ore:dyePink>]]);
recipes.addShaped(<extrautils2:angelring>, [[<advanced_solar_panels:crafting:5>, <ic2:plate:11>, <advanced_solar_panels:crafting:5>], [<ic2:plate:11>, <titantrinkets:DragonTitanCatalyst>, <ic2:plate:11>], [<advanced_solar_panels:crafting:5>, <ic2:plate:11>, <advanced_solar_panels:crafting:5>]]);
recipes.addShaped(<vc:airship_balloon>, [[<ore:fabricHemp>, <ore:fabricHemp>, <ore:fabricHemp>], [<ore:fabricHemp>, <immersiveengineering:metalDecoration0>, <ore:fabricHemp>], [<ore:fabricHemp>, <ore:fabricHemp>, <ore:fabricHemp>]]);
recipes.addShaped(<ironbackpacks:basicBackpack>, [[<ore:fabricHemp>, <ore:fabricHemp>, <ore:fabricHemp>], [<ore:fabricHemp>, <ore:chest>, <ore:fabricHemp>], [<ore:fabricHemp>, <ore:fabricHemp>, <ore:fabricHemp>]]);
recipes.addShaped(<mysticalagriculture:infusion_crystal>, [[<mysticalagriculture:inferium_essence>, <titantrinkets:RefinedRedstone>, <mysticalagriculture:inferium_essence>], [<titantrinkets:RefinedRedstone>, <actuallyadditions:itemCrystal:2>, <titantrinkets:RefinedRedstone>], [<mysticalagriculture:inferium_essence>, <titantrinkets:RefinedRedstone>, <mysticalagriculture:inferium_essence>]]);
recipes.addShaped(<titantrinkets:RefinedRedstone>, [[<minecraft:redstone>, <mysticalagriculture:prosperity_shard>, <minecraft:redstone>], [<mysticalagriculture:prosperity_shard>, <minecraft:redstone>, <mysticalagriculture:prosperity_shard>], [<minecraft:redstone>, <mysticalagriculture:prosperity_shard>, <minecraft:redstone>]]);
recipes.addShaped(<minecraft:furnace>, [[<ore:compressedcobblestone>, <extrautils2:compressedcobblestone>, <extrautils2:compressedcobblestone>], [<ore:compressedcobblestone>, null, <ore:compressedcobblestone>], [<ore:compressedcobblestone>, <ore:compressedcobblestone>, <ore:compressedcobblestone>]]);
recipes.addShaped(<mikedongles:watering_dongle>, [[<ore:ingotIron>, <ore:listAllwater>, null], [<minecraft:iron_ingot>, <actuallyadditions:blockMisc:9>, <minecraft:iron_ingot>], [<ore:ingotIron>, <ore:dye>, <ore:ingotIron>]]);
recipes.addShaped(<minecraft:piston>, [[<ore:plankTreatedWood>, <ore:plankTreatedWood>, <ore:plankTreatedWood>], [<ore:cobblestone>, <ore:ingotIron>, <ore:cobblestone>], [<ore:cobblestone>, <ore:gearRedstone>, <ore:cobblestone>]]);
recipes.addShaped(<actuallyadditions:blockAtomicReconstructor>, [[<ore:ingotIron>, <enderio:itemBasicCapacitor>, <ore:ingotIron>], [<enderio:itemBasicCapacitor>, <actuallyadditions:blockMisc:9>, <enderio:itemBasicCapacitor>], [<ore:ingotIron>, <enderio:itemBasicCapacitor>, <ore:ingotIron>]]);
recipes.addShaped(<actuallyadditions:blockMisc:9>, [[<ore:ingotIron>, <ore:ingotSteel>, <ore:ingotIron>], [<ore:ingotSteel>, <ore:gemQuartzBlack>, <ore:ingotSteel>], [<ore:ingotIron>, <ore:ingotSteel>, <ore:ingotIron>]]);
recipes.addShaped(<enderio:itemMachinePart>, [[<ore:barsIron>, <ore:ingotSteel>, <ore:barsIron>], [<ore:ingotSteel>, <enderio:itemBasicCapacitor>, <ore:ingotSteel>], [<ore:barsIron>, <ore:ingotSteel>, <ore:barsIron>]]);
recipes.addShaped(<minecraft:chest>, [[<ore:plankTreatedWood>, <ore:plankTreatedWood>, <ore:plankTreatedWood>], [<ore:plankTreatedWood>, null, <ore:plankTreatedWood>], [<ore:plankTreatedWood>, <ore:plankTreatedWood>, <ore:plankTreatedWood>]]);
recipes.addShaped(<minecraft:magma>, [[<minecraft:fire_charge>, <minecraft:fire_charge>], [<minecraft:fire_charge>, <minecraft:fire_charge>]]);
recipes.addShaped(<armorplus:tesla_rod>, [[null, <ore:dyeBlue>, <ore:dyeBlue>], [<ore:dyeBlue>, <ore:stickWood>, <ore:dyeBlue>], [<ore:dyeBlue>, <ore:dyeBlue>, null]]);
recipes.addShaped(<minecraft:bucket>, [[null, null, null], [<ore:plateIron>, null, <ore:plateIron>], [null, <ore:plateIron>, null]]);

recipes.addShaped(<titantrinkets:DarkTitanRelic>, [[<bigreactors:minerals>, <bigreactors:minerals>, <bigreactors:minerals>], [<bigreactors:minerals>, <actuallyadditions:itemCrystalEmpowered:4>, <bigreactors:minerals>], [<bigreactors:minerals>, <bigreactors:minerals>, <bigreactors:minerals>]]);


recipes.addShaped(<avaritiaadditions:collector>, [[<avaritia:matrix_ingot>, <avaritia:matrix_ingot>, <avaritia:matrix_ingot>], [<avaritiaadditions:endest_pearl>, <avaritiaadditions:endest_pearl>, <avaritiaadditions:endest_pearl>], [<avaritia:matrix_ingot>, <immersiveengineering:metalDevice1:1>, <avaritia:matrix_ingot>]]);
recipes.addShaped(<avaritiaadditions:neutronium_compressor>, [[<avaritia:matrix_ingot>, <avaritiaadditions:endest_pearl>, <avaritia:matrix_ingot>], [<advgenerators:TurbineAdvAlloy>, <rftools:screen>, <advgenerators:TurbineAdvAlloy>], [<avaritia:matrix_ingot>, <avaritiaadditions:endest_pearl>, <avaritia:matrix_ingot>]]);
recipes.addShaped(<avaritiaadditions:endest_pearl>, [[<minecraft:nether_star>, <titantrinkets:OpenEyeOfEnder>, <minecraft:nether_star>], [<titantrinkets:OpenEyeOfEnder>, <enderio:blockIngotStorage:2>, <titantrinkets:OpenEyeOfEnder>], [<minecraft:nether_star>, <titantrinkets:OpenEyeOfEnder>, <minecraft:nether_star>]]);
recipes.addShaped(<avaritiaadditions:infinity_catalyst>, [[<ore:ingotCrystalMatrix>, <avaritiaadditions:lead_singularity>, <ore:ingotCrystalMatrix>], [<avaritiaadditions:tin_singularity>, <ore:netherStar>, <avaritiaadditions:silver_singularity>], [<ore:ingotCrystalMatrix>, <avaritiaadditions:nickel_singularity>, <ore:ingotCrystalMatrix>]]);
recipes.addShaped(<armorplus:ender_dragon_scale>, [[<ic2:misc_resource:3>, <ic2:misc_resource:3>, <ic2:misc_resource:3>], [<ic2:misc_resource:3>, <adinferos:infernal_feather>, <ic2:misc_resource:3>], [<ic2:misc_resource:3>, <ic2:misc_resource:3>, <ic2:misc_resource:3>]]);
recipes.addShaped(<armorplus:wither_bone>, [[<ic2:misc_resource:3>, <ic2:misc_resource:3>, <ic2:misc_resource:3>], [<ic2:misc_resource:3>, <ore:bone>, <ic2:misc_resource:3>], [<ic2:misc_resource:3>, <ic2:misc_resource:3>, <ic2:misc_resource:3>]]);
recipes.addShaped(<sccraftingrunes:ItemCommonMat>, [[<ic2:misc_resource:3>, <ic2:misc_resource:3>, <ic2:misc_resource:3>], [<ic2:misc_resource:3>, <ore:itemSlag>, <ic2:misc_resource:3>], [<ic2:misc_resource:3>, <ic2:misc_resource:3>, <ic2:misc_resource:3>]]);
recipes.addShaped(<enderio:itemBasicCapacitor:1>, [[null, <ore:ingotEnergeticAlloy>, null], [<enderio:itemBasicCapacitor>, <ore:circuitAdvanced>, <enderio:itemBasicCapacitor>], [null, <ore:ingotEnergeticAlloy>, null]]);
recipes.addShaped(<enderio:itemBasicCapacitor>, [[null, <ore:nuggetGold>, <ore:dustRedstone>], [<ore:nuggetGold>, <ic2:crafting:1>, <ore:nuggetGold>], [<ore:dustRedstone>, <ore:nuggetGold>, null]]);
recipes.addShaped(<immersiveengineering:material:23>, [[<ore:plateSteel>, <immersiveengineering:tool:1>]]);
recipes.addShaped(<advgenerators:EuOutputIV>, [[<advanced_solar_panels:crafting:5>, <ic2:te:80>, <advanced_solar_panels:crafting:5>], [<advgenerators:PowerIO>, <extrautils2:opinium:2>, <advgenerators:PowerIO>], [<advanced_solar_panels:crafting:5>, <ic2:te:80>, <advanced_solar_panels:crafting:5>]]);
recipes.addShaped(<advgenerators:EuOutputEV>, [[<advgenerators:IronFrame>, <advanced_solar_panels:crafting:2>, <advgenerators:IronFrame>], [<advgenerators:PowerIO>, <ic2:te:79>, <advgenerators:PowerIO>], [<advgenerators:IronFrame>, <advanced_solar_panels:crafting:2>, <advgenerators:IronFrame>]]);
recipes.addShaped(<advgenerators:EuOutputHV>, [[<advgenerators:IronFrame>, <ic2:crafting:4>, <advgenerators:IronFrame>], [<advgenerators:PowerIO>, <ic2:te:78>, <advgenerators:PowerIO>], [<advgenerators:IronFrame>, <ic2:crafting:4>, <advgenerators:IronFrame>]]);
recipes.addShaped(<enderio:darkSteel_boots>, [[null, null, null], [<enderio:itemMaterial:15>, null, <enderio:itemMaterial:15>], [<ore:ingotDarkSteel>, null, <ore:ingotDarkSteel>]]);
recipes.addShaped(<enderio:darkSteel_leggings>, [[<ore:ingotDarkSteel>, <enderio:itemMaterial:15>, <enderio:itemAlloy:6>], [<ore:ingotDarkSteel>, null, <ore:ingotDarkSteel>], [<ore:ingotDarkSteel>, null, <ore:ingotDarkSteel>]]);
recipes.addShaped(<enderio:darkSteel_chestplate>, [[<ore:ingotDarkSteel>, null, <enderio:itemAlloy:6>], [<ore:ingotDarkSteel>, <ore:itemPrecientCrystal>, <ore:ingotDarkSteel>], [<ore:ingotDarkSteel>, <ore:ingotDarkSteel>, <ore:ingotDarkSteel>]]);
recipes.addShaped(<enderio:darkSteel_helmet>, [[<ore:ingotDarkSteel>, <ore:itemPrecientCrystal>, <enderio:itemAlloy:6>], [<ore:ingotDarkSteel>, null, <ore:ingotDarkSteel>]]);
recipes.addShaped(<extrautils2:wateringcan:1000>, [[<minecraft:dye:2>, <minecraft:dye:2>, <minecraft:dye:2>], [<tconstruct:faucet>, <itank:tank>, <minecraft:dye:2>], [<minecraft:dye:2>, <minecraft:dye:2>, <minecraft:dye:2>]]);
recipes.addShaped(<armorplus:high_tech_bench>, [[<minecraft:redstone_block>, <minecraft:redstone_block>, <minecraft:redstone_block>], [<armorplus:compressed_obsidian>, <armorplus:workbench>,<armorplus:compressed_obsidian>], [<armorplus:compressed_obsidian>, null, <armorplus:compressed_obsidian>]]);
recipes.addShaped(<armorplus:ender_dragon_arrow> * 16, [[<ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>], [<ore:enderpearl>, <prefab:item_bundle_of_timber>, <ore:enderpearl>], [<ore:enderpearl>, <ore:enderpearl>, <ore:enderpearl>]]);
recipes.addShaped(<minecraft:soul_sand> * 8, [[<ore:sand>, null, null], [<ore:sand>, <ore:witherBone>, <ore:sand>], [<ore:sand>, <ore:sand>, <ore:sand>]]);
recipes.addShaped(<minecraft:soul_sand>, [[<minecraft:rotten_flesh>, <minecraft:rotten_flesh>, <minecraft:rotten_flesh>], [<minecraft:rotten_flesh>, <minecraft:sand>, <minecraft:rotten_flesh>], [<minecraft:rotten_flesh>, <minecraft:rotten_flesh>, <minecraft:rotten_flesh>]]);
recipes.addShaped(<minecraft:hopper>, [[<ore:ingotIron>, <minecraft:chest>, <ore:ingotIron>], [<minecraft:iron_ingot>, <enderio:itemMachinePart:1>, <ore:ingotIron>], [null, <minecraft:iron_ingot>, null]]);
recipes.addShaped(<titantrinkets:ChaosBlock>, [[<forge:bucketFilled>.withTag({FluidName:"rocket_fuel", Amount:1000}), <immersiveengineering:stoneDecoration:3>, <forge:bucketFilled>.withTag({FluidName:"rocket_fuel", Amount:1000})], [<immersiveengineering:stoneDecoration:3>, <minecraft:magma>, <immersiveengineering:stoneDecoration:3>], [<forge:bucketFilled>.withTag({FluidName:"rocket_fuel", Amount:1000}), <immersiveengineering:stoneDecoration:3>, <forge:bucketFilled>.withTag({FluidName:"rocket_fuel", Amount:1000})]]);
recipes.addShaped(<minecraft:magma>, [[<immersiveengineering:material:7>, <ore:itemSlag>, <immersiveengineering:material:7>], [<ore:itemSlag>, <minecraft:lava_bucket>, <ore:itemSlag>], [<ore:itemSlag>, <immersiveengineering:material:7>, <immersiveengineering:material:7>]]);
recipes.addShaped(<enderio:itemMaterial:2> * 4, [[<ore:itemRubber>, <ore:itemClay>, <ore:itemRubber>], [<ore:sand>, <ore:itemRubber>, <ore:sand>], [<ore:itemRubber>, <ore:itemClay>, <ore:itemRubber>]]);
recipes.addShaped(<minecraft:stone_hoe>, [[<ore:cobblestone>, <ore:cobblestone>], [null, <ore:stickWood>], [null, <ore:stickWood>]]);
recipes.addShaped(<minecraft:brick>, [[<dmonsters:dump>, <ore:itemSlag>]]);
recipes.addShaped(<randomthings:fertilizedDirt> * 6, [[<dmonsters:dump>, <dmonsters:dump>, <dmonsters:dump>], [<dmonsters:dump>, <ore:dirt>, <dmonsters:dump>], [<dmonsters:dump>, <dmonsters:dump>, <dmonsters:dump>]]);
recipes.addShaped(<dmonsters:dump>, [[<dmonsters:dump:1>, <dmonsters:dump:1>]]);
recipes.addShaped(<dmonsters:dump:1>, [[<dmonsters:dump:2>, <dmonsters:dump:2>]]);
recipes.addShaped(<dmonsters:dump:2>, [[<dmonsters:dump:3>, <dmonsters:dump:3>]]);
recipes.addShaped(<actuallyadditions:itemWorm>, [[<dmonsters:dump>, <dmonsters:dump>, <dmonsters:dump>], [<dmonsters:dump>, <ore:wheat_seeds>, <dmonsters:dump>], [<dmonsters:dump>, <dmonsters:dump>, <dmonsters:dump>]]);
recipes.addShaped(<ic2:crafting> * 6, [[<dmonsters:dump>, <dmonsters:dump>, <dmonsters:dump>], [<dmonsters:dump>, <ore:itemSlag>, <dmonsters:dump>], [<dmonsters:dump>, <dmonsters:dump>, <dmonsters:dump>]]);
recipes.addShaped(<baublesstuff:Upgrade_Stone>, [[<thermalfoundation:material:1027>, <abyssalcraft:darkstone_cobble>, <ore:dustPetrotheum>], [<abyssalcraft:darkstone_cobble>, <minecraft:lapis_block>, <abyssalcraft:darkstone_cobble>], [<ore:dustPetrotheum>, <abyssalcraft:darkstone_cobble>, <ore:dustPetrotheum>]]);
recipes.addShaped(<avaritiaadditions:deadrock>, [[<enderio:blockIngotStorage:7>, <draconicevolution:draconium_block>, <enderio:blockIngotStorage:7>], [<draconicevolution:draconium_block>, <enderio:blockIngotStorage:7>, <draconicevolution:draconium_block>], [<enderio:blockIngotStorage:7>, <draconicevolution:draconium_block>, <enderio:blockIngotStorage:7>]]);
recipes.addShaped(<titantrinkets:ChaosBlock>, [[<thermalfoundation:storage_alloy:5>, <ore:blockVibrantAlloy>, <ore:blockSignalum>], [<enderio:blockIngotStorage:2>, <ore:blockSignalum>, <enderio:blockIngotStorage:2>], [<ore:blockSignalum>, <ore:blockVibrantAlloy>, <thermalfoundation:storage_alloy:5>]]);
recipes.addShaped(<avaritiaadditions:infinity_catalyst>, [[<avaritiaadditions:infinity_block>, <ore:blockMagnesium>, <avaritiaadditions:infinity_block>], [<nuclearcraft:ingot_block:7>, <avaritiaadditions:infinity_block>, <ore:blockMagnesium>], [<avaritiaadditions:infinity_block>, <nuclearcraft:ingot_block:7>, <avaritiaadditions:infinity_block>]]);
recipes.addShaped(<avaritiaadditions:infinity_ingot>, [[<ore:blockChimerite>, <arsmagica2:block:2>, <ore:blockChimerite>], [<ore:blockMythril>, <nuclearcraft:ingot_block:7>, <ore:blockMythril>], [<ore:blockChimerite>, <arsmagica2:block:2>, <ore:blockChimerite>]]);
recipes.addShaped(<avaritia:matrix_ingot>, [[<minecraft:diamond_block>, <minecraft:diamond_block>, <minecraft:diamond_block>], [<minecraft:diamond_block>, <ore:blockChimerite>, <minecraft:diamond_block>], [<minecraft:diamond_block>, <minecraft:diamond_block>, <minecraft:diamond_block>]]);
recipes.addShaped(<enderio:blockTransceiver>, [[<thermalfoundation:material:295>, <enderio:itemAlloy>, <thermalfoundation:material:295>], [<enderio:itemAlloy>, <enderio:itemFrankenSkull:3>, <enderio:itemAlloy>], [<thermalfoundation:material:295>, <enderio:itemAlloy>, <thermalfoundation:material:295>]]);
recipes.addShaped(<extrautils2:quarry>, [[<extrautils2:passivegenerator:8>, <draconicevolution:energy_crystal:1>, <extrautils2:passivegenerator:8>], [<draconicevolution:energy_crystal:1>, <enderio:blockTransceiver>, <draconicevolution:energy_crystal:1>], [<extrautils2:passivegenerator:8>, <draconicevolution:energy_crystal:1>, <extrautils2:passivegenerator:8>]]);
recipes.addShaped(<chickenchunks:chickenChunkLoader>, [[null, <chickenchunks:chickenChunkLoader:1>, null], [<chickenchunks:chickenChunkLoader:1>, <ore:blockSignalum>, <chickenchunks:chickenChunkLoader:1>], [<ore:blockOnyx>, <chickenchunks:chickenChunkLoader:1>, <simpleores:onyx_block>]]);
recipes.addShaped(<chickenchunks:chickenChunkLoader:1>, [[null, <titantrinkets:OpenEyeOfEnder>, null], [<titantrinkets:OpenEyeOfEnder>, <ore:blockSignalum>, <titantrinkets:OpenEyeOfEnder>], [<simpleores:onyx_block>, <titantrinkets:OpenEyeOfEnder>, <ore:blockOnyx>]]);
recipes.addShaped(<extrautils2:chunkloader>, [[<ore:ingotDarkSoularium>, <ore:ingotDarkSoularium>, <ore:ingotDarkSoularium>], [<ore:ingotDarkSoularium>, <titantrinkets:DragonTitanCatalyst>, <ore:ingotDarkSoularium>], [null, <ore:ingotDarkSoularium>, null]]);
recipes.addShaped(<mob_grinding_utils:saw_upgrade:2>, [[<thermalfoundation:material:1024>, <thermalfoundation:material:289>, <thermalfoundation:material:1024>], [<thermalfoundation:material:289>, <enderio:blockIngotStorage:3>, <thermalfoundation:material:289>], [<thermalfoundation:material:1024>, <thermalfoundation:material:289>, <thermalfoundation:material:1024>]]);
recipes.addShaped(<mob_grinding_utils:saw_upgrade:3>, [[<armorplus:wither_bone>, <thermalfoundation:material:289>, <armorplus:wither_bone>], [<thermalfoundation:material:289>, <enderio:blockIngotStorage:3>, <thermalfoundation:material:289>], [<armorplus:wither_bone>, <thermalfoundation:material:289>, <armorplus:wither_bone>]]);
recipes.addShaped(<mob_grinding_utils:saw_upgrade:4>, [[<minecraft:fermented_spider_eye>, <thermalfoundation:material:289>, <minecraft:fermented_spider_eye>], [<thermalfoundation:material:289>, <enderio:blockIngotStorage:3>, <thermalfoundation:material:289>], [<minecraft:fermented_spider_eye>, <thermalfoundation:material:289>, <minecraft:fermented_spider_eye>]]);
recipes.addShaped(<mob_grinding_utils:saw_upgrade:1>, [[<minecraft:waterlily>, <ore:gearElectrum>, <minecraft:waterlily>], [<ore:gearElectrum>, <ore:blockRedstoneAlloy>, <ore:gearElectrum>], [<minecraft:waterlily>, <ore:gearElectrum>, <minecraft:waterlily>]]);
recipes.addShaped(<mob_grinding_utils:absorption_upgrade>, [[<minecraft:sponge>, <ore:gearElectrum>, <minecraft:sponge>], [<ore:gearElectrum>, <ore:blockRedstoneAlloy>, <ore:gearElectrum>], [<minecraft:sponge>, <ore:gearElectrum>, <minecraft:sponge>]]);
recipes.addShaped(<mob_grinding_utils:saw_upgrade>, [[<armorplus:redstone_sword>, <ore:gearElectrum>, <armorplus:redstone_sword>], [<ore:gearElectrum>, <ore:blockRedstoneAlloy>, <ore:gearElectrum>], [<armorplus:redstone_sword>, <ore:gearElectrum>, <armorplus:redstone_sword>]]);
recipes.addShaped(<mob_grinding_utils:fan_upgrade:2>, [[<adinferos:infernal_feather>, <ore:gearElectrum>, <adinferos:infernal_feather>], [<ore:gearElectrum>, <ore:blockRedstoneAlloy>, <ore:gearElectrum>], [<adinferos:infernal_feather>, <ore:gearElectrum>, <adinferos:infernal_feather>]]);
recipes.addShaped(<mob_grinding_utils:fan_upgrade>, [[<adinferos:infernal_feather>, <adinferos:infernal_feather>, <adinferos:infernal_feather>], [<thermalfoundation:material:289>, <ore:blockRedstoneAlloy>, <thermalfoundation:material:289>], [<adinferos:infernal_feather>, <adinferos:infernal_feather>, <adinferos:infernal_feather>]]);
recipes.addShaped(<mob_grinding_utils:fan_upgrade:1>, [[<adinferos:infernal_feather>, <ore:gearElectrum>, <adinferos:infernal_feather>], [<adinferos:infernal_feather>, <ore:blockRedstoneAlloy>, <adinferos:infernal_feather>], [<adinferos:infernal_feather>, <ore:gearElectrum>, <adinferos:infernal_feather>]]);
recipes.addShaped(<mob_grinding_utils:saw_upgrade:5>, [[<ore:itemSkull>, <ore:gearElectrum>, <ore:itemSkull>], [<ore:itemSkull>, <ore:blockRedstoneAlloy>, <ore:itemSkull>], [<ore:itemSkull>, <ore:gearElectrum>, <ore:itemSkull>]]);
recipes.addShaped(<thermalfoundation:material:513>, [[null, <ore:dustRedstone>, <ore:dustRedstone>], [<ore:dustRedstone>, <thermalfoundation:material:289>, <ore:dustRedstone>], [<ore:dustRedstone>, <ore:dustRedstone>, null]]);
recipes.addShaped(<thermalfoundation:material:515>, [[<ore:dustRedstone>, <ore:dustRedstone>, null], [<ore:dustRedstone>, <ore:gearNickel>, <ore:dustRedstone>], [null, <ore:dustRedstone>, <ore:dustRedstone>]]);
recipes.addShaped(<nuclearcraft:part:2>, [[<ore:plateEnderium>, <ore:ingotUranium238Oxide>, <ore:plateEnderium>], [<ore:ingotUranium238Oxide>, <ore:plateAdvanced>, <ore:ingotUranium238Oxide>], [<ore:plateEnderium>, <ore:ingotUranium238Oxide>, <ore:plateEnderium>]]);
recipes.addShaped(<nuclearcraft:part:1>, [[<ore:blockRedstone>, <ore:ingotTough>, <ore:blockRedstone>], [<ore:ingotTough>, <ore:plateBasic>, <ore:ingotTough>], [<ore:blockRedstone>, <ore:ingotTough>, <ore:blockRedstone>]]);
recipes.addShaped(<nuclearcraft:cooler:7>, [[<ore:dustCryotheum>, <ore:dustCryotheum>, <ore:dustCryotheum>], [<ore:dustCryotheum>, <nuclearcraft:cooler>, <ore:dustCryotheum>], [<ore:dustCryotheum>, <ore:dustCryotheum>, <ore:dustCryotheum>]]);
recipes.addShaped(<nuclearcraft:cooler:5>, [[<ore:glowstone>, <ore:glowstone>, <ore:glowstone>], [<ore:glowstone>, <nuclearcraft:cooler>, <ore:glowstone>], [<ore:glowstone>, <ore:glowstone>, <ore:glowstone>]]);
recipes.addShaped(<nuclearcraft:cooler:6>, [[null, <ore:blockEnderium>, null], [<ore:blockEnderium>, <nuclearcraft:cooler>, <ore:blockEnderium>], [null, <ore:blockEnderium>, null]]);
recipes.addShaped(<nuclearcraft:cooler:4>, [[<ore:blockRedstone>, <ore:blockRedstone>, <ore:blockRedstone>], [<ore:blockRedstone>, <nuclearcraft:cooler>, <ore:blockRedstone>], [<ore:blockRedstone>, <ore:blockRedstone>, <ore:blockRedstone>]]);
recipes.addShaped(<nuclearcraft:cooler:1>, [[<ore:blockPackedIce>, <ore:blockPackedIce>, <ore:blockPackedIce>], [<ore:blockPackedIce>, <nuclearcraft:cooler>, <ore:blockPackedIce>], [<ore:blockPackedIce>, <ore:blockPackedIce>, <ore:blockPackedIce>]]);
recipes.addShaped(<nuclearcraft:cooler>, [[<ore:ingotTough>, <ore:plateDenseSteel>, <ore:ingotTough>], [<ore:plateDenseSteel>, null, <ore:plateDenseSteel>], [<ore:ingotTough>, <ore:plateDenseSteel>, <ore:ingotTough>]]);
recipes.addShaped(<nuclearcraft:cell_block>, [[<ore:ingotTough>, <ore:blockGlassHardened>, <ore:ingotTough>], [<ore:blockGlassHardened>, null, <ore:blockGlassHardened>], [<ore:ingotTough>, <ore:blockGlassHardened>, <ore:ingotTough>]]);
recipes.addShaped(<nuclearcraft:fission_block:1> * 2, [[<enderio:blockDarkIronBars>, <ore:plateBasic>, <enderio:blockDarkIronBars>], [<ore:plateBasic>, <ore:blockObsidian>, <ore:plateBasic>], [<enderio:blockDarkIronBars>, <ore:plateBasic>, <enderio:blockDarkIronBars>]]);
recipes.addShaped(<nuclearcraft:fission_block> * 2, [[<ore:plateSignalum>, <ore:plateBasic>, <ore:plateSignalum>], [<ore:plateBasic>, <ore:ingotTough>, <ore:plateBasic>], [<ore:plateSignalum>, <ore:plateBasic>, <ore:plateSignalum>]]);
recipes.addShaped(<baublesstuff:Exp_Stuff>, [[null, <ore:gearAluminum>, null], [<ore:plateAluminum>, <enderio:itemXpTransfer>, <ore:plateAluminum>], [null, <ore:gearAluminum>, null]]);
recipes.addShaped(<actuallyadditions:blockXPSolidifier>, [[<actuallyadditions:itemCrystalEmpowered:4>, <enderio:itemAlloy:2>, <actuallyadditions:itemCrystalEmpowered:4>], [<thermalfoundation:material:514>, <extrautils2:machine>, <thermalfoundation:material:514>], [<actuallyadditions:itemCrystalEmpowered:4>, <enderio:itemAlloy:2>, <actuallyadditions:itemCrystalEmpowered:4>]]);
recipes.addShaped(<baublesstuff:BlockExpGenerator>, [[<ore:gearAluminum>, <extrautils2:machine>, <ore:gearAluminum>], [<thermalfoundation:material:514>, <actuallyadditions:blockXPSolidifier>, <thermalfoundation:material:514>], [<ore:gearAluminum>, <extrautils2:machine>, <ore:gearAluminum>]]);
recipes.addShaped(<baublesstuff:Pendant_Core>, [[<tconstruct:pan_head>.withTag({Material:"electrum"}), <tconstruct:pan_head>.withTag({Material:"electrum"}), <tconstruct:pan_head>.withTag({Material:"electrum"})], [<adinferos:infernal_feather>, null, <adinferos:infernal_feather>], [<tconstruct:pan_head>.withTag({Material:"electrum"}), <adinferos:infernal_feather>, <tconstruct:pan_head>.withTag({Material:"electrum"})]]);
recipes.addShaped(<baublesstuff:Ring_NotLMagnet>, [[<tconstruct:pan_head>.withTag({Material:"electrum"}), <tconstruct:pan_head>.withTag({Material:"electrum"}), <tconstruct:pan_head>.withTag({Material:"electrum"})], [<tconstruct:pan_head>.withTag({Material:"electrum"}), <baublesstuff:Ring_Magnet>, <tconstruct:pan_head>.withTag({Material:"electrum"})], [<tconstruct:pan_head>.withTag({Material:"electrum"}), <ore:blockChimerite>, <tconstruct:pan_head>.withTag({Material:"electrum"})]]);
recipes.addShaped(<baublesstuff:Ring_Magnet>, [[<tconstruct:pan_head>.withTag({Material:"electrum"}), <tconstruct:pan_head>.withTag({Material:"electrum"}), <tconstruct:pan_head>.withTag({Material:"electrum"})], [<tconstruct:pan_head>.withTag({Material:"electrum"}), null, <tconstruct:pan_head>.withTag({Material:"electrum"})], [<tconstruct:pan_head>.withTag({Material:"electrum"}), <ore:blockChimerite>, <tconstruct:pan_head>.withTag({Material:"electrum"})]]);
recipes.addShaped(<baublesstuff:Ring_Core>, [[<tconstruct:pan_head>.withTag({Material:"electrum"}), <tconstruct:pan_head>.withTag({Material:"electrum"}), <tconstruct:pan_head>.withTag({Material:"electrum"})], [<tconstruct:pan_head>.withTag({Material:"electrum"}), null, <tconstruct:pan_head>.withTag({Material:"electrum"})], [<tconstruct:pan_head>.withTag({Material:"electrum"}), <tconstruct:pan_head>.withTag({Material:"electrum"}), <tconstruct:pan_head>.withTag({Material:"electrum"})]]);
recipes.addShaped(<baublesstuff:Belt_Core>, [[<ore:fabricHemp>, <ore:fabricHemp>, <ore:fabricHemp>], [<ore:fabricHemp>, null, <ore:fabricHemp>], [<ore:fabricHemp>, <ore:blockElectrum>, <ore:fabricHemp>]]);
recipes.addShaped(<immersiveengineering:wirecoil:1>, [[<ore:wireElectrum>, <ore:wireElectrum>, <ore:wireElectrum>], [<ore:wireElectrum>, <ore:stickTreatedWood>, <ore:wireElectrum>], [<ore:wireElectrum>, <ore:wireElectrum>, <ore:wireElectrum>]]);
recipes.addShaped(<immersiveengineering:material:5>, [[<immersiveengineering:wirecoil:3>, <immersiveengineering:wirecoil:3>, <immersiveengineering:wirecoil:3>], [<immersiveengineering:wirecoil:3>, <immersiveengineering:material>, <immersiveengineering:wirecoil:3>], [<immersiveengineering:wirecoil:3>, <immersiveengineering:wirecoil:3>, <immersiveengineering:wirecoil:3>]]);
recipes.addShaped(<immersiveengineering:wirecoil:3>, [[<ore:fiberHemp>, <ore:fiberHemp>, <ore:fiberHemp>], [<ore:fiberHemp>, <ore:stickTreatedWood>, <ore:fiberHemp>], [<ore:fiberHemp>, <ore:fiberHemp>, <ore:fiberHemp>]]);
recipes.addShaped(<immersiveengineering:bullet:2> * 16, [[<immersiveengineering:bullet>, <immersiveengineering:material:7>, <immersiveengineering:bullet>], [<immersiveengineering:bullet>, <ore:ingotSilver>, <immersiveengineering:bullet>], [<immersiveengineering:bullet>, <ore:dustPyrotheum>, <immersiveengineering:bullet>]]);
recipes.addShaped(<immersiveengineering:bullet:2> * 16, [[<immersiveengineering:bullet>, <thermalfoundation:material:1024>, <immersiveengineering:bullet>], [<immersiveengineering:bullet>, <ore:ingotSilver>, <immersiveengineering:bullet>], [<immersiveengineering:bullet>, <ore:dustPyrotheum>, <immersiveengineering:bullet>]]);
recipes.addShaped(<immersiveengineering:bullet:2> * 16, [[<immersiveengineering:bullet>, <minecraft:pumpkin_seeds>, <immersiveengineering:bullet>], [<immersiveengineering:bullet>, <ore:ingotSilver>, <immersiveengineering:bullet>], [<immersiveengineering:bullet>, <ore:dustPyrotheum>, <immersiveengineering:bullet>]]);
recipes.addShaped(<immersiveengineering:bullet:2> * 16, [[<immersiveengineering:bullet>, <ore:gunpowder>, <immersiveengineering:bullet>], [<immersiveengineering:bullet>, <ore:ingotSilver>, <immersiveengineering:bullet>], [<immersiveengineering:bullet>, <ore:dustPyrotheum>, <immersiveengineering:bullet>]]);
recipes.addShaped(<immersiveengineering:bullet:2> * 16, [[<immersiveengineering:bullet>, <ore:itemFlint>, <immersiveengineering:bullet>], [<immersiveengineering:bullet>, <ore:ingotSilver>, <immersiveengineering:bullet>], [<immersiveengineering:bullet>, <ore:dustPyrotheum>, <immersiveengineering:bullet>]]);
recipes.addShaped(<simplyjetpacks:itemJetpack:5>, [[<enderio:blockIngotStorage:2>, <ore:gearSilver>, <enderio:blockIngotStorage:2>], [<draconicevolution:draconic_ingot>, <simplyjetpacks:itemJetpack:4>, <draconicevolution:draconic_ingot>], [<simplyjetpacks:metaItemMods:7>, <ore:gearSilver>, <simplyjetpacks:metaItemMods:7>]]);
recipes.addShaped(<simplyjetpacks:itemJetpack:4>, [[<enderio:blockIngotStorage:1>, <advanced_solar_panels:crafting:13>, <enderio:blockIngotStorage:1>], [<draconicevolution:draconic_ingot>, <thermalexpansion:frame:128>, <draconicevolution:draconic_ingot>], [<simplyjetpacks:metaItemMods:6>, null, <simplyjetpacks:metaItemMods:6>]]);
recipes.addShaped(<simplyjetpacks:itemJetpack:3>.withTag({sjData:{Energy: 600000}}), [[<simplyjetpacks:metaItemMods:11>, <ore:gearSilver>, <simplyjetpacks:metaItemMods:11>], [<simplyjetpacks:metaItemMods:11>, <thermalexpansion:frame:128>, <simplyjetpacks:metaItemMods:11>], [<simplyjetpacks:metaItemMods:5>, <ore:gearSilver>, <simplyjetpacks:metaItemMods:5>]]);
recipes.addShaped(<simplyjetpacks:itemJetpack:2>.withTag({sjData:{Energy: 150000}}), [[<simplyjetpacks:metaItemMods:10>, <enderio:itemBasicCapacitor:2>, <simplyjetpacks:metaItemMods:10>], [<simplyjetpacks:metaItemMods:10>, <thermalexpansion:frame:128>, <simplyjetpacks:metaItemMods:10>], [<simplyjetpacks:metaItemMods:4>, <ore:gearSilver>, <simplyjetpacks:metaItemMods:4>]]);
recipes.addShaped(<extrautils2:flattransfernode> * 2, [[<thermalfoundation:material:1024>, <extrautils2:pipe>, <thermalfoundation:material:1024>], [<abyssalcraft:dspplate>, <ore:chest>, <abyssalcraft:dspplate>]]);
recipes.addShaped(<extrautils2:flattransfernode:1> * 2, [[<ore:dustCryotheum>, <extrautils2:pipe>, <ore:dustCryotheum>], [<abyssalcraft:dspplate>, <ore:chest>, <abyssalcraft:dspplate>]]);
recipes.addShaped(<extrautils2:grocket:2> * 2, [[<thermalfoundation:material:1025>, <extrautils2:pipe>, <thermalfoundation:material:1025>], [<abyssalcraft:darkstone>, <ore:chest>, <abyssalcraft:darkstone>]]);
recipes.addShaped(<extrautils2:grocket> * 2, [[<thermalfoundation:material:1024>, <extrautils2:pipe>, <ore:dustPyrotheum>], [<abyssalcraft:darkstone>, <ore:chest>, <abyssalcraft:darkstone>]]);
recipes.addShaped(<storagedrawers:compDrawers>, [[<ore:ingotSilver>, <ore:gearTin>, <ore:ingotSilver>], [<minecraft:piston>, <ore:drawerBasic>, <minecraft:piston>], [<ore:gearTin>, <ore:ingotSilver>, <ore:gearTin>]]);
recipes.addShaped(<rftools:charged_porter>, [[<ore:gearSilver>, <titantrinkets:OpenEyeOfEnder>, <ore:gearSilver>], [<titantrinkets:OpenEyeOfEnder>, <ore:circuitAdvanced>, <titantrinkets:OpenEyeOfEnder>], [<ore:gearSilver>, <titantrinkets:OpenEyeOfEnder>, <ore:gearSilver>]]);
recipes.addShaped(<immersiveengineering:drillhead>, [[<thermalfoundation:material:160>, <thermalfoundation:material:160>, null], [<thermalfoundation:material:257>, <thermalfoundation:material:257>, <thermalfoundation:material:160>], [<thermalfoundation:material:160>, <thermalfoundation:material:160>, null]]);
recipes.addShaped(<actuallyadditions:itemDrill:3>, [[<ore:gearTin>, <immersiveengineering:drillhead>, <thermalfoundation:material:257>], [<actuallyadditions:itemMisc:8>, <actuallyadditions:blockGrinder>, <actuallyadditions:itemMisc:8>], [<actuallyadditions:blockCrystal:5>, <actuallyadditions:itemMisc:16>, <actuallyadditions:blockCrystal:5>]]);
recipes.addShaped(<thermalexpansion:dynamo>, [[null, <ore:blockRedstone>, null], [<thermalfoundation:material:515>, <enderio:itemMachinePart:1>, <thermalfoundation:material:515>], [<enderio:itemMachinePart:1>, <thermalexpansion:frame>, <enderio:itemMachinePart:1>]]);
recipes.addShaped(<thermalexpansion:dynamo:1>, [[null, <ore:blockRedstone>, null], [<thermalfoundation:material:514>, <enderio:itemMachinePart:1>, <thermalfoundation:material:514>], [<enderio:itemMachinePart:1>, <thermalexpansion:frame>, <enderio:itemMachinePart:1>]]);
recipes.addShaped(<thermalfoundation:material:514>, [[null, <ore:dustRedstone>, <ore:dustRedstone>], [<ore:dustRedstone>, <ore:gearSilver>, <ore:dustRedstone>], [<ore:dustRedstone>, <ore:dustRedstone>, null]]);
recipes.addShaped(<teslacorelib:gear_iron>, [[null, <ore:ingotIron>, null], [<ore:ingotIron>, <ore:stickWood>, <ore:ingotIron>], [null, <ore:ingotIron>, null]]);
recipes.addShaped(<thermalfoundation:material:24>, [[null, <ore:ingotIron>, null], [<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>], [null, <ore:ingotIron>, null]]);
recipes.addShaped(<thermalexpansion:frame:128>, [[<ore:ingotSteel>, <ic2:crafting:2>, <ore:ingotSteel>], [<ore:blockGlassColorless>, <enderio:itemBasicCapacitor:2>, <ore:blockGlassColorless>], [<ore:ingotSteel>, <ic2:crafting:2>, <ore:ingotSteel>]]);
recipes.addShaped(<thermalexpansion:frame:64>, [[<ore:ingotSteel>, <refinedstorage:cable>, <ore:ingotSteel>], [<minecraft:glass>, <ic2:crafting:2>, <ore:blockGlassColorless>], [<ore:ingotSteel>, <refinedstorage:cable>, <ore:ingotSteel>]]);
recipes.addShaped(<thermalexpansion:frame>, [[<ore:ingotSteel>, <refinedstorage:cable>, <ore:ingotSteel>], [<ore:blockGlass>, <ic2:crafting:1>, <ore:blockGlass>], [<ore:ingotSteel>, <refinedstorage:cable>, <ore:ingotSteel>]]);
recipes.addShaped(<extrautils2:pipe> * 8, [[<ic2:crafting>, <ic2:crafting>, <ic2:crafting>], [<ore:blockGlassColorless>, <ore:blockGlassColorless>, <ore:blockGlassColorless>], [<ic2:crafting>, <ic2:crafting>, <ic2:crafting>]]);
recipes.addShaped(<immersiveengineering:metalDevice1:6>, [[<ore:plateTin>, <ore:itemRubber>, <ore:plateTin>], [<ore:plateTin>, <ore:itemRubber>, <ore:plateTin>]]);
recipes.addShaped(<advgenerators:TurbineRotorEnderium>, [[<advgenerators:TurbineBladeEnderium>, <advgenerators:TurbineBladeEnderium>, <advgenerators:TurbineBladeEnderium>], [<advgenerators:TurbineBladeEnderium>, <extrautils2:opinium:4>, <advgenerators:TurbineBladeEnderium>], [<advgenerators:TurbineBladeEnderium>, <advgenerators:TurbineBladeEnderium>, <advgenerators:TurbineBladeEnderium>]]);
recipes.addShaped(<advgenerators:TurbineBladeEnderium> * 2, [[<ore:ingotEnderium>, <ore:ingotEnderium>], [<ore:ingotEnderium>, <ore:ingotEnderium>], [null, <ore:ingotEnderium>]]);
recipes.addShaped(<extrautils2:passivegenerator:8>, [[<extrautils2:decorativesolid:3>, <advanced_solar_panels:crafting:13>, <extrautils2:decorativesolid:3>], [<ore:gearRedstone>, <extrautils2:ingredients:2>, <ore:gearRedstone>], [<extrautils2:decorativesolid:3>, <advanced_solar_panels:crafting:13>, <extrautils2:decorativesolid:3>]]);
recipes.addShaped(<extrautils2:passivegenerator:2>, [[<extrautils2:decorativesolid:3>, <extrautils2:ingredients:1>, <extrautils2:decorativesolid:3>], [<ore:gearNickel>, <minecraft:magma>, <ore:gearNickel>], [<extrautils2:decorativesolid:3>, <extrautils2:decorativesolid:3>, <extrautils2:decorativesolid:3>]]);
recipes.addShaped(<extrautils2:passivegenerator:3>, [[<extrautils2:decorativesolid:3>, <ore:gearNickel>, <extrautils2:decorativesolid:3>], [<extrautils2:ingredients:1>, <ore:eyeofredstone>, <ore:gearRedstone>], [<extrautils2:decorativesolid:3>, <ore:gearNickel>, <extrautils2:decorativesolid:3>]]);
recipes.addShaped(<actuallyadditions:blockFarmer>, [[<actuallyadditions:blockCrystal:5>, <ore:gearNickel>, <actuallyadditions:blockCrystal:5>], [<thermalfoundation:material:261>, <actuallyadditions:blockMisc:9>, <ore:gearNickel>], [<actuallyadditions:blockCrystal:5>, <stevescarts:CartModule:14>, <actuallyadditions:blockCrystal:5>]]);
recipes.addShaped(<actuallyadditions:itemDrillUpgradeFortuneII>, [[<ore:gearElectrum>, <thermalfoundation:material:513>, <ore:gearElectrum>], [<thermalfoundation:material:513>, <actuallyadditions:blockCrystalEmpowered:2>, <thermalfoundation:material:513>], [<ore:gearElectrum>, <thermalfoundation:material:513>, <ore:gearElectrum>]]);
recipes.addShaped(<actuallyadditions:itemDrillUpgradeFortune>, [[<ore:gearElectrum>, <thermalfoundation:material:514>, <ore:gearElectrum>], [<thermalfoundation:material:514>, <actuallyadditions:blockCrystalEmpowered:2>, <thermalfoundation:material:514>], [<ore:gearElectrum>, <thermalfoundation:material:514>, <ore:gearElectrum>]]);
recipes.addShaped(<actuallyadditions:itemDrillUpgradeFiveByFive>, [[<actuallyadditions:itemCrystalEmpowered:2>, <thermalfoundation:material:293>, <actuallyadditions:itemCrystalEmpowered:2>], [<thermalfoundation:material:293>, <actuallyadditions:itemMisc:8>, <thermalfoundation:material:293>], [<actuallyadditions:itemCrystalEmpowered:2>, <thermalfoundation:material:293>, <actuallyadditions:itemCrystalEmpowered:2>]]);
recipes.addShaped(<actuallyadditions:itemDrillUpgradeThreeByThree>, [[<actuallyadditions:itemCrystalEmpowered:2>, <ore:gearElectrum>, <actuallyadditions:itemCrystalEmpowered:2>], [<ore:gearElectrum>, <actuallyadditions:itemMisc:7>, <ore:gearElectrum>], [<actuallyadditions:itemCrystalEmpowered:2>, <ore:gearElectrum>, <actuallyadditions:itemCrystalEmpowered:2>]]);
recipes.addShaped(<actuallyadditions:itemDrillUpgradeSpeedIII>, [[<actuallyadditions:itemCrystal:5>, <thermalfoundation:material:295>, <actuallyadditions:itemCrystal:5>], [<thermalfoundation:material:295>, <actuallyadditions:itemCrystalEmpowered:4>, <thermalfoundation:material:295>], [<actuallyadditions:itemCrystal:5>, <thermalfoundation:material:295>, <actuallyadditions:itemCrystal:5>]]);
recipes.addShaped(<actuallyadditions:itemDrillUpgradeSpeedII>, [[<actuallyadditions:itemCrystal:5>, <thermalfoundation:material:293>, <actuallyadditions:itemCrystal:5>], [<thermalfoundation:material:293>, <actuallyadditions:itemCrystalEmpowered:2>, <thermalfoundation:material:293>], [<actuallyadditions:itemCrystal:5>, <thermalfoundation:material:293>, <actuallyadditions:itemCrystal:5>]]);
recipes.addShaped(<actuallyadditions:itemDrillUpgradeSpeed>, [[<actuallyadditions:itemCrystal:5>, <thermalfoundation:material:289>, <actuallyadditions:itemCrystal:5>], [<thermalfoundation:material:289>, <actuallyadditions:itemCrystal>, <thermalfoundation:material:289>], [<actuallyadditions:itemCrystal:5>, <thermalfoundation:material:289>, <actuallyadditions:itemCrystal:5>]]);
recipes.addShaped(<immersiveengineering:metalDevice1:13>, [[<thermalfoundation:glass:3>, <immersiveengineering:metalDecoration2:4>, <thermalfoundation:glass:3>], [<thermalfoundation:glass:3>, <sccraftingrunes:ItemCommonMat>, <thermalfoundation:glass:3>], [<ore:plankTreatedWood>, <immersiveengineering:material:8>, <ore:plankTreatedWood>]]);
recipes.addShaped(<kitchensink:deathsSythe>, [[<kitchensink:netherStarPlate>, <kitchensink:deathIngot>, <kitchensink:deathIngot>],[null, <kitchensink:DemonicSword>.anyDamage(), <kitchensink:deathIngot>], [null, <kitchensink:deathIngot>, <kitchensink:deathIngot>]]);