// File generated by MineTweakerRecipeMaker
//                     READ THIS HEADER BEFORE EDITING ANYTHING
// ================================================================================
//     This file is read and changed by the mod.
//     If you remove/edit any of the markers, IT WILL STOP WORKING!
//     If you want to make manual edits, make a backup of this file!
//     Markers look like this: "//#MARKER something"
//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
//     Removes come first, then stuff is added.
// ================================================================================
//

// ================================================================================
//#MARKER REMOVE
recipes.remove(<thermalexpansion:augment:336>);
recipes.remove(<minefactoryreloaded:machine_1:9>);
recipes.remove(<minefactoryreloaded:machine_block>);
recipes.remove(<fluxnetworks:FluxController>);
recipes.remove(<fluxnetworks:FluxPoint>);
recipes.remove(<fluxnetworks:FluxPlug>);
recipes.remove(<refinedstorage:network_transmitter>);
recipes.remove(<fluxnetworks:FluxCore>);
recipes.remove(<minefactoryreloaded:machine_2:1>);
recipes.remove(<minefactoryreloaded:machine_2>);
recipes.remove(<harvestcraft:fruitpunchitem>);
recipes.remove(<thermaldynamics:ThermalDynamics_0:6>);
recipes.remove(<thermaldynamics:ThermalDynamics_0>);
recipes.remove(<xreliquary:mob_ingredient:11>);
recipes.remove(<farmingforblockheads:market>);
recipes.remove(<itank:tank>);
recipes.remove(<baublesstuff:Sheet_Harvest>);
recipes.remove(<baublesstuff:Upgrade_Harvest>);
recipes.remove(<nuclearcraft:boots_boron>);
recipes.remove(<nuclearcraft:legs_boron>);
recipes.remove(<nuclearcraft:chest_boron>);
recipes.remove(<nuclearcraft:helm_boron>);
recipes.remove(<mikedongles:dirt_dongle>);
recipes.remove(<kitchensink:obsidianPlate>);
recipes.remove(<tinker_io:smart_output>);
recipes.remove(<tinker_io:fuel_input_machine>);
recipes.remove(<thermalexpansion:tank>);
recipes.remove(<enderio:blockInventoryPanel>);
recipes.remove(<storagedrawers:controller>);
recipes.remove(<notenoughwands:building_wand>);
recipes.remove(<vc:modules/airship_module>);
recipes.remove(<extrautils2:itembuilderswand>);
recipes.remove(<xreliquary:holy_hand_grenade>);
recipes.remove(<vc:modules/airship_module>);
recipes.remove(<agricraft:crop_sticks>);
recipes.remove(<bloodmagic:BlockDemonBricks2:5>);
recipes.remove(<tconstruct:tooltables>);
recipes.remove(<nuclearcraft:axe_boron>);
recipes.remove(<nuclearcraft:pickaxe_boron>);
recipes.remove(<nuclearcraft:sword_boron>);
recipes.remove(<minecraft:stone> * 4);
recipes.remove(<agricraft:agri_nugget:3>);



// ================================================================================
//#MARKER REMOVE SHAPELESS


// ================================================================================
//#MARKER REMOVE SHAPED
recipes.removeShaped(<minecraft:stone> * 4, [[<minecraft:stonebrick>]]);



// ================================================================================
//#MARKER ADD

// ================================================================================
//#MARKER ADD SHAPELESS
recipes.addShapeless(<mysticalagriculture:yellorium_seeds>, [<mysticalagriculture:uranium_seeds>]);
recipes.addShapeless(<harvestcraft:fruitpunchitem> * 5, [<ore:foodApplejuice>, <ore:foodCranberryjuice>, <ore:foodStrawberryjuice>, <ore:foodGrapefruitjuice>, <ore:foodCherryjuice>]);
recipes.addShapeless(<ic2:crafting:23> * 2, [<adinferos:wither_dust>]);
recipes.addShapeless(<ic2:crafting:23> * 2, [<darkutils:material>]);
recipes.addShapeless(<ic2:crafting:23> * 2, [<ore:dropofevil>]);
recipes.addShapeless(<thermalfoundation:material:772> * 4, [<ore:fuelCoke>, <ore:fuelCoke>, <ore:fuelCoke>, <thermalfoundation:material:771>]);
recipes.addShapeless(<minecraft:dye:15> * 4, [<animalium:bear_claw>]);
recipes.addShapeless(<openmodularturrets:ammo_meta:1> * 24, [<ore:gunpowder>, <ore:ingotCopper>, <ore:ingotCopper>]);
recipes.addShapeless(<tconstruct:tooltables>, [<jacb:betterBench>]);
recipes.addShapeless(<minecraft:dye:15> * 8, [<dragonrealm:DragonScale>]);
recipes.addShapeless(<thermalfoundation:ore:5> * 2, [<nethermetals:nether_nickel_ore>]);
recipes.addShapeless(<thermalfoundation:ore:6> * 2, [<nethermetals:nether_platinum_ore>]);
recipes.addShapeless(<ic2:resource:4> * 2, [<nethermetals:nether_uranium_ore>]);
recipes.addShapeless(<nuclearcraft:ore:7> * 2, [<nethermetals:nether_magnesium_ore>]);
recipes.addShapeless(<refinedstorage:silicon>, [<ore:itemSilicon>]);
recipes.addShapeless(<openmodularturrets:turret_base:4>, [<bloodmagic:BlockDemonBricks2:5>]);
recipes.addShapeless(<minecraft:slime_ball>, [<dmonsters:dump>, <ore:dye>]);
recipes.addShapeless(<minecraft:stone> * 9, [<prefab:block_compressed_stone>]);
recipes.addShapeless(<immersiveengineering:metal:29> * 8, [<ore:ingotIron>]);




// ================================================================================
//#MARKER ADD SHAPED
recipes.addShaped(<minefactoryreloaded:machine_1:9>, [[<ore:blockSlime>, <enderio:itemFrankenSkull:1>, <ore:blockSlime>], [<minefactoryreloaded:safari_net_jailer_fancy>, <minefactoryreloaded:machine_block>, <minefactoryreloaded:safari_net_jailer_fancy>], [<ore:blockSlime>, <enderio:itemFrankenSkull:1>, <ore:blockSlime>]]);
recipes.addShaped(<minefactoryreloaded:machine_block>, [[<ore:sheetPlastic>, <ore:sheetPlastic>, <ore:sheetPlastic>], [<ore:sheetPlastic>, <ore:circuitBasic>, <ore:sheetPlastic>], [<ore:sheetPlastic>, <ore:sheetPlastic>, <ore:sheetPlastic>]]);
recipes.addShaped(<fluxnetworks:FluxController>, [[<ore:ingotDarkSteel>, <fluxnetworks:FluxCore>, <ore:ingotDarkSteel>], [<fluxnetworks:FluxCore>, <minefactoryreloaded:rednet_logic>, <fluxnetworks:FluxCore>], [<ore:ingotDarkSteel>, <fluxnetworks:FluxCore>, <ore:ingotDarkSteel>]]);
recipes.addShaped(<fluxnetworks:FluxPoint>, [[<fluxnetworks:FluxCore>, null, <fluxnetworks:FluxCore>], [null, <refinedstorage:network_transmitter>, null], [<fluxnetworks:FluxCore>, null, <fluxnetworks:FluxCore>]]);
recipes.addShaped(<fluxnetworks:FluxPlug>, [[null, <fluxnetworks:FluxCore>, null], [<fluxnetworks:FluxCore>, <refinedstorage:network_transmitter>, <fluxnetworks:FluxCore>], [null, <fluxnetworks:FluxCore>, null]]);
recipes.addShaped(<refinedstorage:network_transmitter>, [[<refinedstorage:wireless_transmitter>, <refinedstorage:processor:3>, <refinedstorage:wireless_transmitter>], [<ore:gearEnderium>, <thermalexpansion:frame:128>, <ore:gearEnderium>], [<refinedstorage:quartz_enriched_iron>, <refinedstorage:quartz_enriched_iron>, <refinedstorage:quartz_enriched_iron>]]);
recipes.addShaped(<fluxnetworks:FluxCore> * 4, [[<fluxnetworks:Flux>, <thermaldynamics:ThermalDynamics_0:4>, <fluxnetworks:Flux>], [<thermaldynamics:ThermalDynamics_0:4>, <titantrinkets:OpenEyeOfEnder>, <thermaldynamics:ThermalDynamics_0:4>], [<fluxnetworks:Flux>, <thermaldynamics:ThermalDynamics_0:4>, <fluxnetworks:Flux>]]);
recipes.addShaped(<thermaldynamics:ThermalDynamics_0:6>, [[<ore:itemConduitBinder>, <ore:itemConduitBinder>, <ore:itemConduitBinder>], [<ore:ingotElectrum>, <ore:blockGlassHardened>, <ore:ingotElectrum>], [<ore:itemConduitBinder>, <ore:itemConduitBinder>, <ore:itemConduitBinder>]]);
recipes.addShaped(<thermaldynamics:ThermalDynamics_0> * 6, [[<ore:itemConduitBinder>, <ore:itemConduitBinder>, <ore:itemConduitBinder>], [<ore:ingotLead>, <ore:blockGlassColorless>, <ore:ingotLead>], [<ore:itemConduitBinder>, <ore:itemConduitBinder>, <ore:itemConduitBinder>]]);
recipes.addShaped(<xreliquary:mob_ingredient:11>, [[<ore:ingotSoularium>, <ore:ingotSoularium>, <ore:ingotSoularium>], [<ore:ingotSoularium>, <minecraft:ender_eye>, <ore:ingotSoularium>], [<ore:ingotSoularium>, <ore:ingotSoularium>, <ore:ingotSoularium>]]);
recipes.addShaped(<minecraft:ice> * 2, [[<minecraft:snowball>, <minecraft:snowball>, <minecraft:snowball>], [<minecraft:snowball>, <ore:listAllwater>, <minecraft:snowball>], [<minecraft:snowball>, <minecraft:snowball>, <minecraft:snowball>]]);
recipes.addShaped(<itank:tank>, [[<ore:gearAluminum>, <ore:blockGlassColorless>, <ore:gearAluminum>], [<ore:blockGlassColorless>, <minecraft:bucket>, <ore:blockGlassColorless>], [<ore:gearAluminum>, <ore:blockGlassColorless>, <ore:gearAluminum>]]);
recipes.addShaped(<kitchensink:obsidianPlate>, [[<ore:blockObsidian>, <ore:blockObsidian>, <ore:blockObsidian>], [<ore:blockObsidian>, null, <ore:blockObsidian>], [<ore:blockObsidian>, <ore:blockObsidian>, <ore:blockObsidian>]]);
recipes.addShaped(<tinker_io:smart_output>, [[<ore:blockSeared>, <minecraft:ice>, <ore:blockSeared>], [<minecraft:ice>, null, <minecraft:ice>], [<ore:blockSeared>, <minecraft:ice>, <ore:blockSeared>]]);
recipes.addShaped(<tinker_io:fuel_input_machine>, [[<ore:blockSeared>, <ore:blockSeared>, <ore:blockSeared>], [<ore:blockSeared>, <ore:blockHopper>, <ore:blockSeared>], [<ore:blockSeared>, <ore:blockSeared>, <ore:blockSeared>]]);
recipes.addShaped(<thermalexpansion:tank>, [[<ore:ingotCopper>, <ore:blockGlassColorless>, <ore:ingotCopper>], [<minecraft:glass>, <extrautils2:ingredients:1>, <minecraft:glass>], [<ore:ingotCopper>, <ore:blockGlassColorless>, <ore:ingotCopper>]]);
recipes.addShaped(<enderio:blockInventoryPanel>, [[<enderio:itemAlloy:6>, <enderio:itemFunctionUpgrade>, <enderio:itemAlloy:6>], [<minecraft:structure_void>, <extrautils2:screen>, <minecraft:structure_void>], [<enderio:itemAlloy:6>, <itank:tank>, <enderio:itemAlloy:6>]]);
recipes.addShaped(<storagedrawers:controller>, [[<ore:plateTin>, <ore:plateTin>, <ore:plateTin>], [<minecraft:structure_void>, <storagedrawers:basicDrawers>, <minecraft:structure_void>], [<ore:plateTin>, <ore:gearRedstone>, <ore:plateTin>]]);
recipes.addShaped(<minecraft:spawn_egg>.withTag({EntityTag: {id:"dragonrealm.Scout Dragon"}}), [[<actuallyadditions:itemMisc:15>, <ore:dustPyrotheum>, <actuallyadditions:itemMisc:15>], [<ore:dustPyrotheum>, <ore:egg>, <ore:dustPyrotheum>], [<actuallyadditions:itemMisc:15>, <ore:dustPyrotheum>, <actuallyadditions:itemMisc:15>]]);
recipes.addShaped(<mysticalagriculture:growth_accelerator>, [[<ore:ingotPrudentium>, <ore:blockGlassColorless>, <ore:ingotPrudentium>], [<ore:itemVibrantCrystal>, <ore:blockCopper>, <ore:itemVibrantCrystal>], [<ore:ingotPrudentium>, <ore:blockGlassColorless>, <ore:ingotPrudentium>]]);
recipes.addShaped(<thermalexpansion:cache>, [[<ore:ingotCopper>, <ore:ingotCopper>, <ore:ingotCopper>], [<ore:ingotCopper>, <ore:plankTreatedWood>, <ore:ingotCopper>], [<ore:ingotCopper>, <ore:ingotCopper>, <ore:ingotCopper>]]);
recipes.addShaped(<notenoughwands:building_wand>, [[null, null, <minecraft:brick_block>], [null, <ore:stickTreatedWood>, null], [<ore:stickTreatedWood>, null, null]]);
recipes.addShaped(<xreliquary:holy_hand_grenade> * 4, [[<minecraft:rotten_flesh>, <thermalfoundation:material:258>, <minecraft:rotten_flesh>], [<minecraft:rotten_flesh>, <minecraft:gunpowder>, <minecraft:rotten_flesh>], [<minecraft:rotten_flesh>, <minecraft:gunpowder>, <minecraft:rotten_flesh>]]);
recipes.addShaped(<vc:modules/airship_module>, [[<simpleores:adamantium_ingot>, <simpleores:adamantium_ingot>, <simpleores:adamantium_ingot>], [<sccraftingrunes:ItemCommonMat>, <ic2:plate:11>, <sccraftingrunes:ItemCommonMat>], [<simpleores:adamantium_ingot>, <simpleores:adamantium_ingot>, <simpleores:adamantium_ingot>]]);
recipes.addShaped(<immersiveengineering:woodenDevice0>, [[<immersiveengineering:treatedWood>, <immersiveengineering:treatedWood>, <ore:plankTreatedWood>], [<immersiveengineering:treatedWood>, <immersiveengineering:material>, <ore:plankTreatedWood>], [<ore:plankTreatedWood>, <ore:plankTreatedWood>, <ore:plankTreatedWood>]]);
recipes.addShaped(<agricraft:crop_sticks>, [[<ore:stickTreatedWood>, <ore:stickTreatedWood>], [<ore:stickTreatedWood>, <ore:stickTreatedWood>]]);
recipes.addShaped(<minecraft:spawn_egg>.withTag({RepairCost:0,display:{Name:"Brahemic"},EntityTag: {id:"dragonrealm.Alpha Dragon"}}), [[<ore:dustPetrotheum>, <ore:dustPetrotheum>, <ore:dustPetrotheum>], [<ore:dustPetrotheum>, <titantrinkets:OnyxDippedEgg>, <ore:dustPetrotheum>], [<ore:dustPetrotheum>, <ore:dustPetrotheum>, <ore:dustPetrotheum>]]);
recipes.addShaped(<minecraft:spawn_egg>.withTag({RepairCost:0,display:{Name:"Ju' Li Sioux"},EntityTag: {id:"dragonrealm.Hunter Dragon"}}), [[<ore:dustPyrotheum>, <ore:dustPyrotheum>, <ore:dustPyrotheum>], [<ore:dustPyrotheum>, <titantrinkets:DragonEgg>, <ore:dustPyrotheum>], [<ore:dustPyrotheum>, <ore:dustPyrotheum>, <ore:dustPyrotheum>]]);
recipes.addShaped(<titantrinkets:OnyxDippedEgg>, [[<simpleores:onyx_block>, <sccraftingrunes:ItemCommonMat>, <simpleores:onyx_block>], [<sccraftingrunes:ItemCommonMat>, <armorplus:bauble_cosmetic_dragon>, <sccraftingrunes:ItemCommonMat>], [<simpleores:onyx_block>, <sccraftingrunes:ItemCommonMat>, <simpleores:onyx_block>]]);
recipes.addShaped(<titantrinkets:DragonEgg>, [[<actuallyadditions:itemMisc:15>, <mysticalagriculture:supremium_apple>, <actuallyadditions:itemMisc:15>], [<mysticalagriculture:supremium_apple>, <sccraftingrunes:ItemCommonMat>, <mysticalagriculture:supremium_apple>], [<actuallyadditions:itemMisc:15>, <mysticalagriculture:supremium_apple>, <actuallyadditions:itemMisc:15>]]);
recipes.addShaped(<nuclearcraft:pickaxe_boron>, [[<nuclearcraft:ingot:5>, <ore:blockBoron>, <ore:ingotBoron>], [null, <minecraft:stick>, null], [null, <ore:stickWood>, null]]);
recipes.addShaped(<nuclearcraft:axe_boron>, [[<nuclearcraft:ingot:5>, <ore:blockBoron>], [<nuclearcraft:ingot:5>, <minecraft:stick>], [null, <ore:stickWood>]]);
recipes.addShaped(<nuclearcraft:sword_boron>, [[<ore:blockBoron>], [<ore:blockBoron>], [<ore:stickWood>]]);
recipes.addShaped(<minecraft:stone> * 20, [[null, <mysticalagriculture:stone_essence>, null], [<mysticalagriculture:stone_essence>, <mysticalagriculture:stone_essence>, <mysticalagriculture:stone_essence>], [null, <mysticalagriculture:stone_essence>, null]]);


